exports.GATEWAY_URL = "https://route.lgthinq.com:46030/v1/service/application/gateway-uri";
exports.SVC_CODE = "SVC202";
exports.CLIENT_ID = "LGAO221A02";
exports.OAUTH_SECRET_KEY = "c053c2a6ddeb7ad97cb0eed0dcb31cf8";
exports.OAUTH_CLIENT_KEY = "LGAO722A02";
exports.API_KEY = "VGhpblEyLjAgU0VSVklDRQ==";
exports.API_CLIENT_ID = "0396d48364f9a25824a3121758b512686f0ead3a5a4349b5b76f0febcd1809ea";
exports.API1_CLIENT_ID = "00709966e14709a49926823120fe0807731383782187aa23b87fb70439fac1c8";
exports.MQTT_URL = "https://common.lgthinq.com/route";
exports.MQTT_CER2 = "https://www.amazontrust.com/assets/repository/AmazonRootCA1.pem";
exports.MQTT_CER = "https://www.amazontrust.com/repository/AmazonRootCA1.pem";
exports.MQTT_CER509 = "http://www.tbs-x509.com/Comodo_AAA_Certificate_Services.crt";
exports.MQTT_AZU = "https://lgthinq.azurewebsites.net/api/certdata";
exports.APPLICATION_KEY = "6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9"; // for spx login
exports.APP_AGENT = [
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.7.2; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.7.1; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.6; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.6.1; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.5.1; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 16.5; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 17; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 17.1; Scale/3.00)",
    "LG ThinQ/5.0.11861 (iPhone; iOS 17.1.1; Scale/3.00)",
];
exports.APP_DEVICE = [
    "iPhone 8 Plus",
    "iPhone 8",
    "iPhone 11 Pro",
    "iPhone 9 Plus",
    "iPhone 9",
    "iPhone 10 Plus",
    "iPhone 11",
    "iPhone 11 Plus",
    "iPhone 10",
    "iPhone 12 Plus",
    "iPhone 12",
    "iPhone 12 Pro",
];

exports.PlatformType = {
    ThinQ1: "thinq1",
    ThinQ2: "thinq2",
};

exports.DeviceType = {
    REFRIGERATOR: 101,
    KIMCHI_REFRIGERATOR: 102,
    WATER_PURIFIER: 103,
    WASHER: 201,
    WASHER_2: 221,
    WASH_TOWER: 222,
    DRYER: 202,
    STYLER: 203,
    DISHWASHER: 204,
    OVEN: 301,
    MICROWAVE: 302,
    COOKTOP: 303,
    HOOD: 304,
    AC: 401, // Includes heat pumps, etc., possibly all HVAC devices.
    AIR_PURIFIER: 402,
    DEHUMIDIFIER: 403,
    HOT_WATER_HEAT_PUMP: 406,
    AERO_TOWER: 410,
    ROBOT_KING: 501, // This is Robotic vacuum cleaner
    TV: 701,
    BOILER: 801,
    SPEAKER: 901,
    HOMEVU: 902,
    ARCH: 1001,
    MISSG: 3001,
    SENSOR: 3002,
    SOLAR_SENSOR: 3102,
    IOT_LIGHTING: 3003,
    IOT_MOTION_SENSOR: 3004,
    IOT_SMART_PLUG: 3005,
    IOT_DUST_SENSOR: 3006,
    EMS_AIR_STATION: 4001,
    AIR_SENSOR: 4003,
    PURICARE_AIR_DETECTOR: 4004,
    V2PHONE: 6001,
    HOMEROBOT: 9000,
};

exports.responseCodeText = {
    "0000": "OK",
    "0001": "PARTIAL_OK",
    "0103": "OPERATION_IN_PROGRESS_DEVICE",
    "0007": "PORTAL_INTERWORKING_ERROR",
    "0104": "PROCESSING_REFRIGERATOR",
    "0111": "RESPONSE_DELAY_DEVICE",
    8107: "SERVICE_SERVER_ERROR",
    8102: "SSP_ERROR",
    9020: "TIME_OUT",
    8104: "WRONG_XML_OR_URI",
    9000: "AWS_IOT_ERROR",
    8105: "AWS_S3_ERROR",
    8106: "AWS_SQS_ERROR",
    9002: "BASE64_DECODING_ERROR",
    9001: "BASE64_ENCODING_ERROR",
    8103: "CLIP_ERROR",
    "0105": "CONTROL_ERROR_REFRIGERATOR",
    9003: "CREATE_SESSION_FAIL",
    9004: "DB_PROCESSING_FAIL",
    8101: "DM_ERROR",
    "0013": "DUPLICATED_ALIAS",
    "0008": "DUPLICATED_DATA",
    "0004": "DUPLICATED_LOGIN",
    "0102": "EMP_AUTHENTICATION_FAILED",
    8900: "ETC_COMMUNICATION_ERROR",
    9999: "ETC_ERROR",
    "0112": "EXCEEDING_LIMIT",
    "0119": "EXPIRED_CUSTOMER_NUMBER",
    9007: "EXPIRES_SESSION_BY_WITHDRAWAL",
    "0100": "FAIL",
    8001: "INACTIVE_API",
    "0107": "INSUFFICIENT_STORAGE_SPACE",
    9010: "INVAILD_CSR",
    "0002": "INVALID_BODY",
    "0118": "INVALID_CUSTOMER_NUMBER",
    "0003": "INVALID_HEADER",
    "0301": "INVALID_PUSH_TOKEN",
    "0116": "INVALID_REQUEST_DATA_FOR_DIAGNOSIS",
    "0014": "MISMATCH_DEVICE_GROUP",
    "0114": "MISMATCH_LOGIN_SESSION",
    "0006": "MISMATCH_NONCE",
    "0115": "MISMATCH_REGISTRED_DEVICE",
    9005: "MISSING_SERVER_SETTING_INFORMATION",
    "0110": "NOT_AGREED_TERMS",
    "0106": "NOT_CONNECTED_DEVICE",
    "0120": "NOT_CONTRACT_CUSTOMER_NUMBER",
    "0010": "NOT_EXIST_DATA",
    "0009": "NOT_EXIST_DEVICE",
    "0117": "NOT_EXIST_MODEL_JSON",
    "0121": "NOT_REGISTERED_SMART_CARE",
    "0012": "NOT_SUPPORTED_COMMAND",
    8000: "NOT_SUPPORTED_COUNTRY",
    "0005": "NOT_SUPPORTED_SERVICE",
    "0109": "NO_INFORMATION_DR",
    "0108": "NO_INFORMATION_SLEEP_MODE",
    "0011": "NO_PERMISSION",
    "0113": "NO_PERMISION_MODIFY_RECIPE",
    "0101": "NO_REGISTERED_DEVICE",
    9006: "NO_USER_INFORMATION",
    10000: "UNKNWON_ERROR",
};

exports.deTranslation = {
    ALLERGYCARE: "Allergiepflege",
    TOWELS: "Tücher",
    BULKYITEM: "Bettdecken",
    MIXFABRIC: "Mischgewebe",
    COTTONNORMAL: "Einfache Baumwolle",
    SPORTWEAR: "Sportkleidung",
    QUICKDRY: "30 Minuten",
    DELICATES: "Feinwäsche",
    RACKDRY: "Korbtrocknen",
    COOLAIR: "Abkühlen",
    WARMAIR: "Aufwärmen",
    SHOESFABRICDOLL: "Schuhe / Gewebe-Puppe",
    BABYWEAR: "Babykleidung",
    BLANKETREFRESH: "Decken - Refresh",
    SINGLEGARMENTS: "Einzelstücke",
    DEODORIZATION: "Geruchsbeseitigung",
    EASYIRON: "Leichtes Bügeln",
    ECONOMICDRY: "Eco Trocknen",
    BIGSIZEITEM: "Übergröße",
    FULLSIZELOAD: "Volle Last",
    BABYCARE: "Babybekleidung",
    HYGIENE: "Hygiene",
    SMALLLOAD: "Kleine Beladung",
    LINGERIE: "Lingerie",
    SKINCARE: "Hautpflege",
    COLDWASH: "Kalt waschen",
    RINSESPIN: "Spülen + Schleudern",
    KIDSWEAR: "Kinderbekleidung",
    SCHOOLUNIFORM: "Schuluniform",
    SWIMMINGWEAR: "Badebekleidung",
    RAINYSEASON: "Nasse Kleidung",
    GYMCLOTHES: "Gymnastikbekleidung",
    JEANS: "Jeans",
    BLANKET: "Decke",
    SWEATSTAIN: "Schweißflecken",
    SINGLEGARMENT: "Einzelkleidungsstück",
    COLORPROTECTION: "Farbschutz",
    NOISEMINIMIZE: "Extra leise",
    MINIMIZEWRINKLES: "Knitterschutz",
    LIGHTLYSOILEDITEMS: "Leicht verschmutzte Wäsche",
    MINIMIZEDETERGENT: "Waschmittelrückstände minimieren",
    SLEEVEHEMSANDCOLLARS: "Hemden und Blusen",
    JUICEANDFOODSTAINS: "Lebensmittel-Flecken",
    QUICKTUBCLEAN: "Schnelle Trommelreinigung",
    DRAIN: "Abpumpen",
    SPIN: "Schleudern",
    COTTON: "Koch-/Buntwäsche",
    EASYCARE: "Pflegeleicht",
    COTTONPLUS: "ECO 40-60",
    DUVET: "Bettdecken",
    MIXEDFABRIC: "Mix",
    SPORTSWEAR: "Sportbekleidung",
    SILENTWASH: "Nachtprogramm",
    SPEED14: "14 Minuten",
    TUB_CLEAN: "Trommelreinigung",
    WOOL: "Wolle",
    DELICATE: "Feinwäsche",
    ALLERGYSPASTEAM: "Allergy Care/Hygiene",
    TURBO39: "39 Minuten",
    TURBO59: "59 Minuten",
    DRY: "Trocknen",
    DRY_COOLING: "Abkühlen",
    DRY_NORMAL: "Normales Trocknen",
    DRY_IRON: "Bügeln",
    DRY_ECO: "Öko-Trocknen",
    DRY_SPEED: "Schnell",
    DRY_LOW: "Niedrig",
    DRY_NORMAL_ECO: "Normaler Sparmodus",
    DRY_30: "Trockenzeit 30 Min.",
    DRY_60: "Trockenzeit 60 Min.",
    DRY_90: "Trockenzeit 90 Min.",
    DRY_120: "Trockenzeit 120 Min.",
    NO_SOILWASH: "Keine Verschmutzung",
    SOILWASH_TURBO_WASH: "Schwere Verschmutzung",
    SOILWASH_TIMESAVE: "Zeitsparen Verschmutzung",
    SOILWASH_NORMAL: "Normale Verschmutzung",
    SOILWASH_INTENSIVE: "Intensive Verschmutzung",
    SOILWASH_PREWASH: "Vorwäsche Verschmutzung",
    SOILWASH_SOAKING: "Bodenwäsche und Einweichen",
    SPIN_DRAIN_ONLY: "Nur Schleuderablauf",
    FRESHCARE_OFF: "Frische Pflege aus",
    FRESHCARE_ON: "Frische Pflege an",
    RINSE_1: "Spülen 1",
    RINSE_2: "Spülen 2",
    RINSE_3: "Spülen 3",
    RINSE_4: "Spülen 4",
    RINSE_5: "Spülen 5",
    RINSE_PLUS2: "Spülen Plus 2",
    DRYLEVEL_150MIN: "Trockenzeit 150 Min.",
    NO_SPIN: "Schleudern aus",
    SPIN_400: "400 U/Min",
    SPIN_600: "600 U/Min",
    SPIN_700: "700 U/Min",
    SPIN_800: "800 U/Min",
    SPIN_900: "900 U/Min",
    SPIN_1000: "1000 U/Min",
    SPIN_1100: "1100 U/Min",
    SPIN_1200: "1200 U/Min",
    SPIN_1400: "1400 U/Min",
    SPIN_1600: "1600 U/Min",
    SPIN_Max: "Schleudern Max",
    NOT_SELECTED: "Keine Auswahl",
    TEMP_COLD: "Kalt",
    TEMP_20: "20°C",
    TEMP_30: "30°C",
    TEMP_40: "40°C",
    TEMP_50: "50°C",
    TEMP_60: "60°C",
    TEMP_95: "95°C",
    NO_TEMP: "Keine Auswahl",
    LOADITEM_OFF: "Beladungsmenge aus",
    LOADITEM_1: "Beladungsmenge 1",
    LOADITEM_2: "Beladungsmenge 2",
    LOADITEM_3: "Beladungsmenge 3",
    TURBOWASH_OFF: "Schnell waschen aus",
    TURBOWASH_ON: "Schnell waschen an",
    CREASECARE_OFF: "Knitterschutz aus",
    CREASECARE_ON: "Knitterschutz an",
    STEAMSOFTENER_OFF: "Dampf Weichspüler aus",
    STEAMSOFTENER_ON: "Dampf Weichspüler an",
    ECOHYBRID_OFF: "ECO aus",
    ECOHYBRID_ON: "ECO an",
    MEDICRINSE_OFF: "Medizinische Spülung aus",
    MEDICRINSE_ON: "Medizinische Spülung an",
    RINSE_SPIN_OFF: "Spülen und Schleudern aus",
    RINSE_SPIN_ON: "Spülen und Schleudern an",
    PREWASH_OFF: "Vorwäsche aus",
    PREWASH_ON: "Vorwäsche an",
    STEAM_OFF: "Dampf aus",
    STEAM_ON: "Dampf an",
    INITIAL_BIT_OFF: "Gewichtserkennung aus",
    INITIAL_BIT_ON: "Gewichtserkennung an",
    REMOTE_START_OFF: "Fernzugriff aus",
    REMOTE_START_ON: "Fernzugriff an",
    DOOR_LOCK_OFF: "Türverriegelung aus",
    DOOR_LOCK_ON: "Türverriegelung an",
    CHILDLOCK_OFF: "Kindersicherung aus",
    CHILDLOCK_ON: "Kindersicherung an",
    NO_RINSE: "Kein Spülen",
    RINSE_NORMAL: "Normal",
    RINSE_PLUS: "Spülen+",
    RINSE_PLUSPLUS: "Spülen++",
    RINSE_NORMAL_HOLD: "Normal Spülen",
    RINSE_PLUS_HOLD: "Normal Spülen+",
    courseFL24inchBaseTitan: "Programm",
    smartCourseFL24inchBaseTitan: "Download Programm",
    proofing: "Imprägnieren",
    soilWash: "Verschmutzung",
    spin: "Schleudergang",
    temp: "Temperatur",
    rinse: "Spülen",
    reserveTimeHour: "Startzeit in Stunde(n)",
    reserveTimeMinute: "Startzeit in Minute(n)",
    loadItemWasher: "Beladungsmenge",
    turboWash: "Kurz Waschen",
    creaseCare: "Knitterschutz",
    steamSoftener: "Dampf Weichspüler",
    ecoHybrid: "ECO Hybrid",
    medicRinse: "Medizinische Spülung",
    rinseSpin: "Spülen und Schleudern",
    preWash: "Vorwäsche",
    steam: "Dampf",
    initialBit: "Einschaltverzögerung",
    remoteStart: "Fernstart",
    doorLock: "Türverriegelung",
    childLock: "Kindersicherung",
    SEL_PROGRAM: "Programmauswahl",
    MON_DEVICE: "Geräte Überwachung",
    FAVORITE: "Favorit aus der APP laden",
    LASTCOURSE: "Die letzten 10 Waschgänge",
    STATISTIC: "Energie Statistik",
    PERIOD: "Periode",
    HOURLY: "stündlich",
    DAILY: "täglich",
    MONTHLY: "monatlich",
    YEARLY: "jährlich",
    STARTDATE: "Startdatum im Format YYYY.MM.DD",
    ENDDATE: "Enddatum im Format YYYY.MM.DD",
    JSONRESULT: "Ergebnis der Abfrage",
    SENDREQUEST: "Abfrage versenden",
    NAMEFRIDGE: "Abfrage auswählen",
    F_DOOR: "Tür geöffnet",
    F_DOOR_MONTH: "Tür geöffnet - Monat",
    F_DOOR_DAY: "Tür geöffnet - Tag",
    F_ENERGY: "Energieverbrauch",
    F_ENERGY_MONTH: "Energieverbrauch - Monat",
    F_ENERGY_DAY: "Energieverbrauch - Tag",
    F_WATER: "Wasserverbrauch",
    F_ACTIVE: "Aktiv Stromsparen",
    F_SMARTACTIVE: "Aktiv Samrt-Stromsparen",
    F_FRIDGE: "Wasser Kühlschrank",
    F_SELFCARE: "Eigenreinigung",
    antiCrease: "Knitterschutz",
    dampDryBeep: "Signal Bügelfeucht",
    dnnReady: "DNN Bereit",
    dryLevel: "Trockenstufe",
    handIron: "Bügelfeucht",
    moreLessTime: "Mehr / Weniger Zeit",
    reservation: "Reservierung",
    selfClean: "Selbstreinigung",
    standby: "Standby",
    timeSetting: "Zeiteinstellung",
    ANTICREASE_OFF: "Faltenfrei aus",
    ANTICREASE_ON: "Faltenfrei an",
    DAMPDRYBEEP_OFF: "Signal Bügelfeucht aus",
    DAMPDRYBEEP_ON: "Signal Bügelfeucht an",
    DNNREADY_OFF: "DNN Ready aus",
    DNNREADY_ON: "DNN Ready an",
    NO_DRYLEVEL: "Kein Trocknungsgrad",
    DRYLEVEL_IRON: "Bügeltrocken",
    DRYLEVEL_CUPBOARD: "Schranktrocken",
    DRYLEVEL_EXTRA: "Extra trocken",
    NO_ECOHYBRID: "Energiesparen aus",
    ECOHYBRID_ECO: "Energiesparen",
    ECOHYBRID_NORMAL: "Normal",
    ECOHYBRID_TURBO: "Turbo",
    HANDIRON_OFF: "Bügeltrocken aus",
    HANDIRON_ON: "Bügeltrocken an",
    RESERVATION_OFF: "Reservierung aus",
    RESERVATION_ON: "Reservierung an",
    STANDBY_OFF: "Standby aus",
    STANDBY_ON: "Standby an",
    SELFCLEAN_OFF: "Selbstreinigung aus",
    SELFCLEAN_ON: "Selbstreinigung an",
    MON_UPDATE: "Letzte Update",
    NAMEAIR: "Klimaanlage",
    NAMEHEAT: "Wärmepumpe",
    AIR_ENERGY: "Energie",
    AIR_POLLUTION: "Umweltverschmutzung",
    SUPERDRY: "Super Trocken",
    WM_STATE_POWER_OFF_W: "Aus",
    WM_STATE_INITIAL_W: "Startbereit",
    WM_STATE_PAUSE_W: "Pause",
    WM_STATE_ERROR_AUTO_OFF_W: "Selbstabschaltung wg. Fehler",
    WM_STATE_RESERVE_W: "TBD",
    WM_STATE_DETECTING_W: "Beladungserkennung",
    WM_STATE_ADD_DRAIN_W: "Abpumpen",
    WM_STATE_DETERGENT_AMOUNT_W: "Waschmittelmenge",
    WM_STATE_RUNNING_W: "Läuft",
    WM_STATE_PREWASH_W: "Vorwäsche",
    WM_STATE_RINSING_W: "Spülen",
    WM_STATE_RINSE_HOLD_W: "Einweichen",
    WM_STATE_SPINNING_W: "Schleudern",
    WM_STATE_DRYING_W: "Trocknen",
    WM_STATE_END_W: "Ende",
    WM_STATE_FRESHCARE_W: "TBD",
    WM_STATE_TUBCLEAN_COUNT_ALRAM_W: "Trommelreinigung Alarm",
    WM_STATE_FROZEN_PREVENT_INITIAL_W: "Frost - kein Start",
    WM_STATE_FROZEN_PREVENT_RUNNING_W: "Frost - kein Start",
    WM_STATE_FROZEN_PREVENT_PAUSE_W: "Frost - kein Start",
    WM_STATE_AUDIBLE_DIAGNOSIS_W: "Modus Smarte Diagnose",
    AC_MAIN_OPERATION_RIGHT_ON_W: "Rechts an",
    AC_MAIN_OPERATION_LEFT_ON_W: "Links an",
    AC_MAIN_OPERATION_ALL_ON_W: "Alle an",
    AC_MAIN_OPERATION_MODE_AROMA_W: "Aroma Modus",
    AC_VENT_MODE_HEAT_EXCHANGE_W: "Wärmetauscher Modus",
    AC_VENT_MODE_BYPASS_W: "Bypass Modus",
    AC_VENT_MODE_AUTO_W: "Auto Modus",
    DRYLEVEL_NORMAL: "Normales Trocknen",
    DRYLEVEL_30: "Trockenzeit 30 Minuten",
    DRYLEVEL_60: "Trockenzeit 60 Minuten",
    DRYLEVEL_90: "Trockenzeit 90 Minuten",
    DRYLEVEL_120: "Trockenzeit 120 Minuten",
    DRYLEVEL_150: "Trockenzeit 150 Minuten",
    DRYLEVEL_ECO: "Öko-Trocknen",
    DRYLEVEL_VERY: "Sehr Trocken",
    DRYLEVEL_LOW: "Niedrig",
    DRYLEVEL_ENERGY: "Energie Trocknen",
    DRYLEVEL_SPEED: "Schnelles Trocknen",
    DRYLEVEL_COOLING: "Abkühlen",
    WRINKLECARE_OFF: "Anti-Faltenpflege aus",
    WRINKLECARE_ON: "Anti-Faltenpflege an",
    COURSE_TYPE_DOWNLOADCYCLE: "Download Kurs",
    COURSE_TYPE_RECENT: "Letzte Kurs",
    COURSE_TYPE_MYPATTERN: "Mein Kurs",
    COURSE_TYPE_COURSE: "Type",
    VEGATABLE_STAIN: "Pflanzliche Flecke",
    TOMATOSAUCE: "Tomatensoße",
    TEA: "Tee",
    SOY_SAUCE: "Sojasouce",
    SPINACH: "Spinat",
    SHOE_POLISH: "Schuhcreme",
    RUST: "Rost",
    RED_WINE: "Rotwein",
    PEPPER: "Pfeffer",
    MUD: "Dreck",
    MAKE_UP: "Makeup",
    LIPSTICK: "Lippenstift",
    KETCHUP: "Ketchup",
    GREASE: "Fett",
    GRASS: "Gras",
    FRUIT_STAIN: "Fruchtflecke",
    FATOIL: "Fett",
    EGG: "Ei",
    CURRY: "Curry",
    COLA: "Cola",
    COFFEE: "Kaffee",
    COCOA: "Kakao",
    CHOCOLATE: "Schokolade",
    BLOOD: "Blut",
    pickerOffset: "Picker-Offset",
    MINI_PAIRING_ON: "Mini an",
    MINI_PAIRING_OFF: "Mini aus",
    DETERGENT_BOX_ON: "Waschmittelbox an",
    DETERGENT_BOX_OFF: "Waschmittelbox aus",
    DETERGENT_REMAINING_YES: "Waschmittelrückstände ja",
    DETERGENT_REMAINING_NO: "Waschmittelrückstände nein",
    DETERGENT_ON: "Waschmittel an",
    DETERGENT_OFF: "Waschmittel aus",
    SOFTENER_ON: "Weichspüler an",
    SOFTENER_OFF: "Weichspüler aus",
    PROOFING_ON: "Imprägnieren an",
    PROOFING_OFF: "Imprägnieren aus",
    DRYLEVEL_120MIN: "Trockenzeit 120 Minuten",
    DRYLEVEL_90MIN: "Trockenzeit 90 Minuten",
    DRYLEVEL_60MIN: "Trockenzeit 60 Minuten",
    DRYLEVEL_30MIN: "Trockenzeit 30 Minuten",
    RINSE_HOLD: "Spülen & Halten",
    SOILWASH_HEAVY: "Starke Verschmutzung",
    SOILWASH_LIGHT: "Leichte  Verschmutzung",
    STEAM_8_LEVEL: "Dampf Level 8",
    STEAM_3_LEVEL: "Dampf Level 3",
    STEAM_2_LEVEL: "Dampf Level 2",
    STEAM_1_LEVEL: "Dampf Level 1",
    GPLUS_BEST_WASH_TIMESAVE: "GPlus Zeitersparnis",
    GPLUS_BEST_WASH_TURBOWASH: "GPlus Turbo",
    GPLUS_BEST_WASH_INTENSIVE: "GPlus Intensiv",
    GPLUS_BEST_WASH_NORMAL: "GPlus Normal",
    GPLUS_BEST_WASH_NO_SELECT: "GPlus Keine Auswahl",
    AUTO_DETERGENT_ON: "Automatisch Waschmittel an",
    AUTO_DETERGENT_OFF: "Automatisch Waschmittel aus",
    CP_OFF_EN_W: "Aus",
    CP_ON_EN_W: "An",
    OWNREQUEST: "Eigene JSON Abfrage",
    OWNANSWER: "Antwort JSON Abfrage",
    DRYLEVEL_DAMPDRY: "Bügeltrocken",
    DRYLEVEL_LESSDRY: "Weniger trocken",
    DRYLEVEL_VERYDRY: "Extra trocken",
    0: "0 Minuten",
    20: "20 Minuten",
    30: "30 Minuten",
    40: "40 Minuten",
    50: "50 Minuten",
    60: "60 Minuten",
    80: "80 Minuten",
    90: "90 Minuten",
    100: "100 Minuten",
    120: "120 Minuten",
    150: "150 Minuten",
    180: "180 Minuten",
    210: "210 Minuten",
    240: "240 Minuten",
};

exports.enTranslation = {
    ALLERGYCARE: "Allergy-Care",
    TOWELS: "Towels",
    BULKYITEM: "Bulky",
    MIXFABRIC: "Mix",
    COTTONNORMAL: "Normal Cotton",
    SPORTWEAR: "Sportswear",
    QUICKDRY: "Speed 30",
    DELICATES: "Delicates",
    RACKDRY: "Rack-Dry",
    COOLAIR: "Cool-Air",
    WARMAIR: "Warm-Air",
    SHOESFABRICDOLL: "Shoes / Fabric-doll",
    BABYWEAR: "Baby-wear",
    BLANKETREFRESH: "Blanket-Refresh",
    SINGLEGARMENTS: "Single-Garments",
    DEODORIZATION: "odor elimination",
    EASYIRON: "Easy-Iron",
    ECONOMICDRY: "Eco Dry",
    BIGSIZEITEM: "Big-Size-Item",
    FULLSIZELOAD: "Full-Size-Load",
    BABYCARE: "Baby-care",
    HYGIENE: "Hygiene",
    SMALLLOAD: "Small load",
    LINGERIE: "Lingerie",
    SKINCARE: "Skin care",
    COLDWASH: "Cold wash",
    RINSESPIN: "Rinse + Spin",
    KIDSWEAR: "Kidswear",
    SCHOOLUNIFORM: "School-uniform",
    SWIMMINGWEAR: "Swimming wear",
    RAINYSEASON: "Rain season",
    GYMCLOTHES: "Gym-clothes",
    JEANS: "Jeans",
    BLANKET: "Blanket",
    SWEATSTAIN: "Sweat stain",
    SINGLEGARMENT: "Single garment",
    COLORPROTECTION: "Color protection",
    NOISEMINIMIZE: "Noise minimize",
    MINIMIZEWRINKLES: "Minimize wrinkles",
    LIGHTLYSOILEDITEMS: "Lightly soiled items",
    MINIMIZEDETERGENT: "Minimize detergent",
    SLEEVEHEMSANDCOLLARS: "Shirts and blouses",
    JUICEANDFOODSTAINS: "Juice and foods stains",
    QUICKTUBCLEAN: "Quick tub cleanup",
    DRAIN: "Drain",
    SPIN: "Spin",
    COTTON: "Cotton",
    EASYCARE: "Easy-care",
    COTTONPLUS: "Cotton+",
    DUVET: "Duvet",
    MIXEDFABRIC: "Mix",
    SPORTSWEAR: "Sportswear",
    SILENTWASH: "Silent wash",
    SPEED14: "14 Minutes",
    TUB_CLEAN: "Tub cleanup",
    WOOL: "Wool",
    DELICATE: "Delicate",
    ALLERGYSPASTEAM: "Allergy",
    TURBO39: "39 Minutes",
    TURBO59: "59 Minutes",
    DRY: "Dry",
    DRY_COOLING: "Cooling",
    DRY_NORMAL: "Normal",
    DRY_IRON: "Iron",
    DRY_ECO: "ECO",
    DRY_SPEED: "Speed",
    DRY_LOW: "Lower",
    DRY_NORMAL_ECO: "Normal ECO",
    DRY_30: "Dryer time 30 Min.",
    DRY_60: "Dryer time 60 Min.",
    DRY_90: "Dryer time 90 Min.",
    DRY_120: "Dryer time 120 Min.",
    NO_SOILWASH: "Not soil",
    SOILWASH_TURBO_WASH: "Soil turbo wash",
    SOILWASH_TIMESAVE: "Soil time save",
    SOILWASH_NORMAL: "Normal soil",
    SOILWASH_INTENSIVE: "Intensive soil",
    SOILWASH_PREWASH: "Prewash soil wash",
    SOILWASH_SOAKING: "Soil wash soaking",
    SPIN_DRAIN_ONLY: "Spin drain only",
    FRESHCARE_OFF: "Fresh care off",
    FRESHCARE_ON: "Fresh care on",
    RINSE_1: "Rinse 1",
    RINSE_2: "Rinse 2",
    RINSE_3: "Rinse 3",
    RINSE_4: "Rinse 4",
    RINSE_5: "Rinse 5",
    RINSE_PLUS2: "Rinse Plus 2",
    DRYLEVEL_150MIN: "Dryer time 150 Min.",
    NO_SPIN: "Spin off",
    SPIN_400: "400 RPM",
    SPIN_600: "600 RPM",
    SPIN_700: "700 RPM",
    SPIN_800: "800 RPM",
    SPIN_900: "900 RPM",
    SPIN_1000: "1000 RPM",
    SPIN_1100: "1100 RPM",
    SPIN_1200: "1200 RPM",
    SPIN_1400: "1400 RPM",
    SPIN_1600: "1600 RPM",
    SPIN_Max: "Spin Max",
    NOT_SELECTED: "No Selected",
    TEMP_COLD: "Cold",
    TEMP_20: "20°C",
    TEMP_30: "30°C",
    TEMP_40: "40°C",
    TEMP_50: "50°C",
    TEMP_60: "60°C",
    TEMP_95: "95°C",
    NO_TEMP: "No temperature",
    LOADITEM_OFF: "Load-item off",
    LOADITEM_1: "Load-item 1",
    LOADITEM_2: "Load-item 2",
    LOADITEM_3: "Load-item 3",
    TURBOWASH_OFF: "Turbo wash off",
    TURBOWASH_ON: "Turbo wash on",
    CREASECARE_OFF: "Crease care off",
    CREASECARE_ON: "Crease care on",
    STEAMSOFTENER_OFF: "Steam softener off",
    STEAMSOFTENER_ON: "Steam softener on",
    ECOHYBRID_OFF: "ECO off",
    ECOHYBRID_ON: "ECO on",
    MEDICRINSE_OFF: "Medic rinse off",
    MEDICRINSE_ON: "Medic rinse on",
    RINSE_SPIN_OFF: "Rinse and Spin off",
    RINSE_SPIN_ON: "Rinse and Spin on",
    PREWASH_OFF: "Prewash off",
    PREWASH_ON: "Prewash on",
    STEAM_OFF: "Steam off",
    STEAM_ON: "Steam on",
    INITIAL_BIT_OFF: "Weight detection off",
    INITIAL_BIT_ON: "Weight detection on",
    REMOTE_START_OFF: "Remote access off",
    REMOTE_START_ON: "Remote access on",
    DOOR_LOCK_OFF: "Door lock off",
    DOOR_LOCK_ON: "Door lock on",
    CHILDLOCK_OFF: "Child lock off",
    CHILDLOCK_ON: "Child lock on",
    NO_RINSE: "No rinse",
    RINSE_NORMAL: "Rinse normal",
    RINSE_PLUS: "Rinse+",
    RINSE_PLUSPLUS: "Rinse++",
    RINSE_NORMAL_HOLD: "Normal rinse",
    RINSE_PLUS_HOLD: "Normal rinse+",
    courseFL24inchBaseTitan: "Program",
    smartCourseFL24inchBaseTitan: "Download Program",
    proofing: "Proofing",
    soilWash: "Soil wash",
    spin: "Spin",
    temp: "Temperature",
    rinse: "Rinse",
    reserveTimeHour: "Start time hour(s)",
    reserveTimeMinute: "Start time Minute(s)",
    loadItemWasher: "Load items",
    turboWash: "Turbo wash",
    creaseCare: "Crease care",
    steamSoftener: "Steam softener",
    ecoHybrid: "ECO Hybrid",
    medicRinse: "Medic rinse",
    rinseSpin: "Rinse and Spin",
    preWash: "Prewash",
    steam: "Steam",
    initialBit: "Weight detection",
    remoteStart: "Remote access",
    doorLock: "Door lock",
    childLock: "Child lock",
    SEL_PROGRAM: "Select Program",
    MON_DEVICE: "Device Monitoring",
    FAVORITE: "Download favorite into the DP WMDownload.",
    LASTCOURSE: "The last 10 washes",
    STATISTIC: "Energy Statistic",
    PERIOD: "Period",
    HOURLY: "hourly",
    DAILY: "daily",
    MONTHLY: "monthly",
    YEARLY: "yearly",
    STARTDATE: "Start date in format YYYY.MM.DD",
    ENDDATE: "End date in format YYYY.MM.DD",
    JSONRESULT: "Result",
    SENDREQUEST: "Send request",
    NAMEFRIDGE: "Select request",
    F_DOOR: "Door open",
    F_DOOR_MONTH: "Door open - Month",
    F_DOOR_DAY: "Door open - Day",
    F_ENERGY: "Energy",
    F_ENERGY_MONTH: "Energy - Month",
    F_ENERGY_DAY: "Energy - Day",
    F_WATER: "Water consumption",
    F_ACTIVE: "Active power saving",
    F_SMARTACTIVE: "Active power smartsaving",
    F_FRIDGE: "Water fridge",
    F_SELFCARE: "Self care",
    antiCrease: "Anti-Crease",
    dampDryBeep: "Damp-Dry-Beep",
    dnnReady: "DNN Ready",
    dryLevel: "Dry-Level",
    handIron: "Hand-Iron",
    moreLessTime: "More / Less Time",
    reservation: "Reservation",
    selfClean: "Self-Clean",
    standby: "Standby",
    timeSetting: "Setting Time",
    ANTICREASE_OFF: "Anti-Crease off",
    ANTICREASE_ON: "Anti-Crease on",
    DAMPDRYBEEP_OFF: "Damp-Dry-Beep off",
    DAMPDRYBEEP_ON: "Damp-Dry-Beep on",
    DNNREADY_OFF: "DNN Ready off",
    DNNREADY_ON: "DNN Ready on",
    NO_DRYLEVEL: "No Dry-Level",
    DRYLEVEL_IRON: "Dry-Level-Iron",
    DRYLEVEL_CUPBOARD: "Dry-Level-Cupboard",
    DRYLEVEL_EXTRA: "Dry-Level-Extra",
    NO_ECOHYBRID: "Save Energy off",
    ECOHYBRID_ECO: "Save Energy",
    ECOHYBRID_NORMAL: "Normal",
    ECOHYBRID_TURBO: "Turbo",
    HANDIRON_OFF: "Hand-Iron off",
    HANDIRON_ON: "Hand-Iron on",
    RESERVATION_OFF: "Reservation off",
    RESERVATION_ON: "Reservation on",
    STANDBY_OFF: "Standby off",
    STANDBY_ON: "Standby on",
    SELFCLEAN_OFF: "Self-Clean off",
    SELFCLEAN_ON: "Self-Clean on",
    MON_UPDATE: "Last Update",
    NAMEAIR: "Air Conditioning",
    NAMEHEAT: "Heat pump",
    AIR_ENERGY: "Energy",
    AIR_POLLUTION: "Pollution",
    SUPERDRY: "Super-dry",
    WM_STATE_POWER_OFF_W: "Off",
    WM_STATE_INITIAL_W: "Starting",
    WM_STATE_PAUSE_W: "Pause",
    WM_STATE_ERROR_AUTO_OFF_W: "Off due to error",
    WM_STATE_RESERVE_W: "TBD",
    WM_STATE_DETECTING_W: "Detecting load",
    WM_STATE_ADD_DRAIN_W: "Draining",
    WM_STATE_DETERGENT_AMOUNT_W: "Amount detergent",
    WM_STATE_RUNNING_W: "Running",
    WM_STATE_PREWASH_W: "Prewashing",
    WM_STATE_RINSING_W: "Rinsing",
    WM_STATE_RINSE_HOLD_W: "Soaking",
    WM_STATE_SPINNING_W: "Spinning",
    WM_STATE_DRYING_W: "Drying",
    WM_STATE_END_W: "End",
    WM_STATE_FRESHCARE_W: "TBD",
    WM_STATE_TUBCLEAN_COUNT_ALRAM_W: "Tub cleaning Alarm",
    WM_STATE_FROZEN_PREVENT_INITIAL_W: "Frost - no start",
    WM_STATE_FROZEN_PREVENT_RUNNING_W: "Frost - no start",
    WM_STATE_FROZEN_PREVENT_PAUSE_W: "Frost - no start",
    WM_STATE_AUDIBLE_DIAGNOSIS_W: "Smart Diagnosis mode",
    AC_MAIN_OPERATION_RIGHT_ON_W: "On right",
    AC_MAIN_OPERATION_LEFT_ON_W: "On left",
    AC_MAIN_OPERATION_ALL_ON_W: "on all",
    AC_MAIN_OPERATION_MODE_AROMA_W: "Aroma Mode",
    AC_VENT_MODE_HEAT_EXCHANGE_W: "Heat Exchange Mode",
    AC_VENT_MODE_BYPASS_W: "Bypass Mode",
    AC_VENT_MODE_AUTO_W: "Auto Mode",
    DRYLEVEL_NORMAL: "Drylevel normal",
    DRYLEVEL_30: "Drylevel 30 Minutes",
    DRYLEVEL_60: "Drylevel 60 Minutes",
    DRYLEVEL_90: "Drylevel 90 Minutes",
    DRYLEVEL_120: "Drylevel 120 Minutes",
    DRYLEVEL_150: "Drylevel 150 Minutes",
    DRYLEVEL_ECO: "ECO-Dry",
    DRYLEVEL_VERY: "Drylevel very",
    DRYLEVEL_LOW: "Drylevel low",
    DRYLEVEL_ENERGY: "Drylevel energy",
    DRYLEVEL_SPEED: "Drylevel speed",
    DRYLEVEL_COOLING: "Drylevel cooling",
    WRINKLECARE_OFF: "Wrinkle care off",
    WRINKLECARE_ON: "Wrinkle care on",
    COURSE_TYPE_DOWNLOADCYCLE: "download course",
    COURSE_TYPE_RECENT: "recent course",
    COURSE_TYPE_MYPATTERN: "my pattern course",
    COURSE_TYPE_COURSE: "Type",
    VEGATABLE_STAIN: "Vegatable stain",
    TOMATOSAUCE: "tomato sauce",
    TEA: "tea",
    SOY_SAUCE: "soy sauce",
    SPINACH: "spinach",
    SHOE_POLISH: "shoe polish",
    RUST: "rust",
    RED_WINE: "red wine",
    PEPPER: "pepper",
    MUD: "mud",
    MAKE_UP: "make up",
    LIPSTICK: "lipstick",
    KETCHUP: "ketchup",
    GREASE: "grease",
    GRASS: "gras",
    FRUIT_STAIN: "fruit stain",
    FATOIL: "fatoil",
    EGG: "egg",
    CURRY: "curry",
    COLA: "cola",
    COFFEE: "coffee",
    COCOA: "cacao",
    CHOCOLATE: "chocolate",
    BLOOD: "blood",
    pickerOffset: "Picker-Offset",
    MINI_PAIRING_ON: "Mini pairing on",
    MINI_PAIRING_OFF: "Mini pairing off",
    DETERGENT_BOX_ON: "detergent box on",
    DETERGENT_BOX_OFF: "detergent box on",
    DETERGENT_REMAINING_YES: "detergent remaining yes",
    DETERGENT_REMAINING_NO: "detergent remaining no",
    DETERGENT_ON: "detergent on",
    DETERGENT_OFF: "detergent off",
    SOFTENER_ON: "softener on",
    SOFTENER_OFF: "softener off",
    PROOFING_ON: "proofing on",
    PROOFING_OFF: "proofing off",
    DRYLEVEL_120MIN: "Dry 120 Minutes",
    DRYLEVEL_90MIN: "Dry 90 Minutes",
    DRYLEVEL_60MIN: "Dry 60 Minutes",
    DRYLEVEL_30MIN: "Dry 30 Minutes",
    RINSE_HOLD: "rinse & hold",
    SOILWASH_HEAVY: "soilwash heavy",
    SOILWASH_LIGHT: "soilwash light",
    STEAM_8_LEVEL: "steam level 8",
    STEAM_3_LEVEL: "steam level 3",
    STEAM_2_LEVEL: "steam level 2",
    STEAM_1_LEVEL: "steam level 1",
    GPLUS_BEST_WASH_TIMESAVE: "GPlus TIMESAVE",
    GPLUS_BEST_WASH_TURBOWASH: "GPlus TURBOWASH",
    GPLUS_BEST_WASH_INTENSIVE: "GPlus INTENSIVE",
    GPLUS_BEST_WASH_NORMAL: "GPlus NORMAL",
    GPLUS_BEST_WASH_NO_SELECT: "GPlus no select",
    AUTO_DETERGENT_ON: "auto detergent on",
    AUTO_DETERGENT_OFF: "auto detergent off",
    CP_OFF_EN_W: "OFF",
    CP_ON_EN_W: "ON",
    OWNREQUEST: "Own JSON request",
    OWNANSWER: "Response request",
    DRYLEVEL_DAMPDRY: "Dry-Level-Iron",
    DRYLEVEL_LESSDRY: "Less dry",
    DRYLEVEL_VERYDRY: "Extra dry",
    0: "0 Minutes",
    20: "20 Minutes",
    30: "30 Minutes",
    40: "40 Minutes",
    50: "50 Minutes",
    60: "60 Minutes",
    80: "80 Minutes",
    90: "90 Minutes",
    100: "100 Minutes",
    120: "120 Minutes",
    150: "150 Minutes",
    180: "180 Minutes",
    210: "210 Minutes",
    240: "240 Minutes",
};
