exports.GATEWAY_URL = "https://route.lgthinq.com:46030/v1/service/application/gateway-uri";
exports.SVC_CODE = "SVC202";
exports.CLIENT_ID = "LGAO221A02";
exports.OAUTH_SECRET_KEY = "c053c2a6ddeb7ad97cb0eed0dcb31cf8";
exports.OAUTH_CLIENT_KEY = "LGAO722A02";
exports.API_KEY = "VGhpblEyLjAgU0VSVklDRQ==";
exports.API_CLIENT_ID = "0396d48364f9a25824a3121758b512686f0ead3a5a4349b5b76f0febcd1809ea";
exports.API1_CLIENT_ID = "00709966e14709a49926823120fe0807731383782187aa23b87fb70439fac1c8";
exports.MQTT_URL = "https://common.lgthinq.com/route";
exports.MQTT_CER = "https://www.amazontrust.com/repository/AmazonRootCA1.pem";
exports.MQTT_AZU = "https://lgthinq.azurewebsites.net/api/certdata";
exports.APPLICATION_KEY = "6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9"; // for spx login

exports.PlatformType = {
    ThinQ1: "thinq1",
    ThinQ2: "thinq2",
};

exports.DeviceType = {
    REFRIGERATOR: 101,
    KIMCHI_REFRIGERATOR: 102,
    WATER_PURIFIER: 103,
    WASHER: 201,
    WASHER_2: 221,
    WASH_TOWER: 222,
    DRYER: 202,
    STYLER: 203,
    DISHWASHER: 204,
    OVEN: 301,
    MICROWAVE: 302,
    COOKTOP: 303,
    HOOD: 304,
    AC: 401, // Includes heat pumps, etc., possibly all HVAC devices.
    AIR_PURIFIER: 402,
    DEHUMIDIFIER: 403,
    ROBOT_KING: 501, // This is Robotic vacuum cleaner
    TV: 701,
    BOILER: 801,
    SPEAKER: 901,
    HOMEVU: 902,
    ARCH: 1001,
    MISSG: 3001,
    SENSOR: 3002,
    SOLAR_SENSOR: 3102,
    IOT_LIGHTING: 3003,
    IOT_MOTION_SENSOR: 3004,
    IOT_SMART_PLUG: 3005,
    IOT_DUST_SENSOR: 3006,
    EMS_AIR_STATION: 4001,
    AIR_SENSOR: 4003,
    PURICARE_AIR_DETECTOR: 4004,
    V2PHONE: 6001,
    HOMEROBOT: 9000,
};

exports.deTranslation = {
    ALLERGYCARE: "Alergiepflege",
    TOWELS: "Tücher",
    BULKYITEM: "Bettdecken",
    MIXFABRIC: "Mischgewebe",
    COTTONNORMAL: "Einfache Baumwolle",
    SPORTWEAR: "Sportkleidung",
    QUICKDRY: "30 Minuten",
    DELICATES: "Feinwäsche",
    RACKDRY: "Korbtrocknen",
    COOLAIR: "Abkühlen",
    WARMAIR: "Aufwärmen",
    SHOESFABRICDOLL: "Schuhe / Gewebe-Puppe",
    BABYWEAR: "Babykleidung",
    BLANKETREFRESH: "Decken - Refresh",
    SINGLEGARMENTS: "Einzelstücke",
    DEODORIZATION: "Geruchsbeseitigung",
    EASYIRON: "Leichtes Bügeln",
    ECONOMICDRY: "Eco Trocknen",
    BIGSIZEITEM: "Übergrösse",
    FULLSIZELOAD: "Volle Last",
    BABYCARE: "Babybekleidung", 
    HYGIENE: "Hygiene", 
    SMALLLOAD: "Kleine Beladung", 
    LINGERIE: "Lingerie", 
    SKINCARE: "Hautpflege", 
    COLDWASH: "Kalt waschen", 
    RINSESPIN: "Spülen + Schleudern", 
    KIDSWEAR: "Kinderbekleidung", 
    SCHOOLUNIFORM: "Schuluniform", 
    SWIMMINGWEAR: "Badebekleidung", 
    RAINYSEASON: "Nasse Kleidung", 
    GYMCLOTHES: "Gymnastikbekleidung", 
    JEANS: "Jeans", 
    BLANKET: "Decke", 
    SWEATSTAIN: "Schweißflecken", 
    SINGLEGARMENT: "Einzelkleidungsstück", 
    COLORPROTECTION: "Farbschutz", 
    NOISEMINIMIZE: "Extra leise", 
    MINIMIZEWRINKLES: "Knitterschutz", 
    LIGHTLYSOILEDITEMS: "Leicht verschmutzte Wäsche", 
    MINIMIZEDETERGENT: "Waschmittelrückstände minimieren", 
    SLEEVEHEMSANDCOLLARS: "Hemden und Blusen", 
    JUICEANDFOODSTAINS: "Lebensmittel-Flecken", 
    QUICKTUBCLEAN: "Schnelle Tommelreinigung", 
    DRAIN: "Abpumpen", 
    SPIN: "Schleudern",
    COTTON: "Koch-/Buntwäsche", 
    EASYCARE: "Pflegeleicht", 
    COTTONPLUS: "ECO 40-60", 
    DUVET: "Bettdecken", 
    MIXEDFABRIC: "Mix", 
    SPORTSWEAR: "Sportbekleidung", 
    SILENTWASH: "Nachtprogramm", 
    SPEED14: "14 Minuten", 
    TUB_CLEAN: "Trommelreinigung", 
    WOOL: "Wolle", 
    DELICATE: "Feinwäsche", 
    ALLERGYSPASTEAM: "Allergy Care/Hygiene", 
    TURBO39: "39 Minuten",
    TURBO59: "59 Minuten",
    DRY: "Trocknen",
    DRY_COOLING: "Abkühlen",
    DRY_NORMAL: "Normales Trocknen",
    DRY_IRON: "Bügeln",
    DRY_ECO: "Öko-Trocknen",
    DRY_SPEED: "Schnell",
    DRY_LOW: "Niedrig",
    DRY_NORMAL_ECO: "Normaler Sparmodus",
    DRY_30: "Trockenzeit 30 Min.",
    DRY_60: "Trockenzeit 60 Min.",
    DRY_90: "Trockenzeit 90 Min.",
    DRY_120: "Trockenzeit 120 Min.",
    NO_SOILWASH: "Keine Verschmutzung",
    SOILWASH_TURBO_WASH: "Schwere Verschmutzung",
    SOILWASH_TIMESAVE: "Zeitsparen Verschmutzung",
    SOILWASH_NORMAL: "Normale Verschmutzung",
    SOILWASH_INTENSIVE: "Intensive Verschmutzung",
    NO_SPIN: "Schleudern aus",
    SPIN_400: "400 U/Min",
    SPIN_600: "600 U/Min",
    SPIN_700: "700 U/Min",
    SPIN_800: "800 U/Min",
    SPIN_900: "900 U/Min",
    SPIN_1000: "1000 U/Min",
    SPIN_1100: "1100 U/Min",
    SPIN_1200: "1200 U/Min",
    SPIN_1400: "1400 U/Min",
    SPIN_1600: "1600 U/Min",
    SPIN_Max: "Schleudern Max",
    NOT_SELECTED: "Keine Auswahl",
    TEMP_COLD: "Kalt",
    TEMP_20: "20°C",
    TEMP_30: "30°C",
    TEMP_40: "40°C",
    TEMP_50: "50°C",
    TEMP_60: "60°C",
    TEMP_95: "95°C",
    NO_TEMP: "Keine Auswahl",
    LOADITEM_OFF: "Beladungsmenge aus",
    LOADITEM_1: "Beladungsmenge 1",
    LOADITEM_2: "Beladungsmenge 2",
    LOADITEM_3: "Beladungsmenge 3",
    TURBOWASH_OFF: "Schnell waschen aus",
    TURBOWASH_ON: "Schnell waschen an",
    CREASECARE_OFF: "Knitterschutz aus",
    CREASECARE_ON: "Knitterschutz an",
    STEAMSOFTENER_OFF: "Dampf Weichspüler aus",
    STEAMSOFTENER_ON: "Dampf Weichspüler an",
    ECOHYBRID_OFF: "ECO aus",
    ECOHYBRID_ON: "ECO an",
    MEDICRINSE_OFF: "Medizinische Spülung aus",
    MEDICRINSE_ON: "Medizinische Spülung an",
    RINSE_SPIN_OFF: "Spülen und Schleudern aus",
    RINSE_SPIN_ON: "Spülen und Schleudern an",
    PREWASH_OFF: "Vorwäsche aus",
    PREWASH_ON: "Vorwäsche an",
    STEAM_OFF: "Dampf aus",
    STEAM_ON: "Dampf an",
    INITIAL_BIT_OFF: "Gewichtserkennung aus",
    INITIAL_BIT_ON: "Gewichtserkennung an",
    REMOTE_START_OFF: "Fernzugriff aus",
    REMOTE_START_ON: "Fernzugriff an",
    DOOR_LOCK_OFF: "Türverschluss aus",
    DOOR_LOCK_ON: "Türverschluss an",
    CHILDLOCK_OFF: "Kindersicherung aus",
    CHILDLOCK_ON: "Kindersicherung an",
    NO_RINSE: "Kein Spülen",
    RINSE_NORMAL: "Normal", 
    RINSE_PLUS: "Spülen+", 
    RINSE_PLUSPLUS: "Spülen++",
    RINSE_NORMAL_HOLD: "Normal Spülen",
    RINSE_PLUS_HOLD: "Normal Spülen+",
    courseFL24inchBaseTitan: "Programm", 
    smartCourseFL24inchBaseTitan: "Download Programm",
    proofing: "Imprägnieren",
    soilWash: "Verschmutzung",
    spin: "Schleudergang",
    temp: "Temperatur",
    rinse: "Spülen",
    reserveTimeHour: "Startzeit in Stunde(n)",
    reserveTimeMinute: "Startzeit in Minute(n)",
    loadItemWasher: "Beladungsmenge", 
    turboWash: "Kurz Waschen",
    creaseCare: "Knitterschutz",
    steamSoftener: "Dampf Weichspüler",
    ecoHybrid: "ECO Hybrid",
    medicRinse: "Medizinische Spülung",
    rinseSpin: "Spülen und Schleudern",
    preWash: "Vorwäsche",
    steam: "Dampf",
    initialBit: "Einschaltverzögerung",
    remoteStart: "Fernzugriff",
    doorLock: "Türverriegelung",
    childLock: "Kinderschutz",
    SEL_PROGRAM: "Programauswahl",
    MON_DEVICE: "Geräte Überwachung",
    FAVORITE: "Favorit aus der APP laden",
    LASTCOURSE: "Die letzten 10 Waschgänge",
    STATISTIC: "Energie Statistik",
    PERIOD: "Periode",
    HOURLY: "stündlich",
    DAILY: "täglich",
    MONTHLY: "monatlich",
    YEARLY: "jährlich",
    STARTDATE: "Startdatum im Format YYYY.MM.DD",
    ENDDATE: "Enddatum im Format YYYY.MM.DD",
    JSONRESULT: "Ergebnis der Abfrage",
    SENDREQUEST: "Abfrage versenden",
    NAMEFRIDGE: "Abfrage auswählen",
    F_DOOR: "Tür geöffnet",
    F_ENERGY: "Energieverbrauch",
    F_WATER: "Wasserverbrauch",
    F_ACTIVE: "Aktiv Stromsparen",
    F_FRIDGE: "Wasser Kühlschrank",
    F_SELFCARE: "Eigenreinigung",
    antiCrease: "Knitterschutz",
    dampDryBeep: "Signal Bügelfeucht",
    dnnReady: "DNN Bereit",
    dryLevel: "Trockenstufe",
    handIron: "Bügelfeucht",
    moreLessTime: "Mehr / Weniger Zeit",
    reservation: "Reservierung",
    selfClean: "Selbstreinigung",
    standby: "Standby",
    timeSetting: "Zeiteinstellung",
    ANTICREASE_OFF: "Faltenfrei aus",
    ANTICREASE_ON: "Faltenfrei an",
    DAMPDRYBEEP_OFF: "Signal Bügelfeucht aus",
    DAMPDRYBEEP_ON: "Signal Bügelfeucht an",
    DNNREADY_OFF: "DNN Ready aus",
    DNNREADY_ON: "DNN Ready an",
    NO_DRYLEVEL: "Kein Trocknungsgrad",
    DRYLEVEL_IRON: "Bügeltrocken",
    DRYLEVEL_CUPBOARD: "Schranktrocken",
    DRYLEVEL_EXTRA: "Extra trocken",
    NO_ECOHYBRID: "Energiesparen aus",
    ECOHYBRID_ECO: "Energiesparen",
    ECOHYBRID_NORMAL: "Normal",
    ECOHYBRID_TURBO: "Turbo",
    HANDIRON_OFF: "Bügeltrocken aus",
    HANDIRON_ON: "Bügeltrocken an",
    RESERVATION_OFF: "Reservierung aus",
    RESERVATION_ON: "Reservierung an",
    STANDBY_OFF: "Standby aus",
    STANDBY_ON: "Standby an",
    SELFCLEAN_OFF: "Selbstreinigung aus",
    SELFCLEAN_ON: "Selbstreinigung an",
    MON_UPDATE: "Letzte Update",
    SUPERDRY: "Super Trocken"
};

exports.enTranslation = {
    ALLERGYCARE: "Allergy-Care",
    TOWELS: "Towels",
    BULKYITEM: "Bulky",
    MIXFABRIC: "Mix",
    COTTONNORMAL: "Normal Cotton",
    SPORTWEAR: "Sportwear",
    QUICKDRY: "Speed 30",
    DELICATES: "Delicates",
    RACKDRY: "Rack-Dry",
    COOLAIR: "Cool-Air",
    WARMAIR: "Warm-Air",
    SHOESFABRICDOLL: "Shoes / Fabric-doll",
    BABYWEAR: "Babywear",
    BLANKETREFRESH: "Blanket-Refresh",
    SINGLEGARMENTS: "Single-Garments",
    DEODORIZATION: "odor elimination",
    EASYIRON: "Easy-Iron",
    ECONOMICDRY: "Eco Dry",
    BIGSIZEITEM: "Big-Size-Item",
    FULLSIZELOAD: "Full-Size-Load",
    BABYCARE: "Babycare", 
    HYGIENE: "Hygiene", 
    SMALLLOAD: "Small load", 
    LINGERIE: "Lingerie", 
    SKINCARE: "Skin care", 
    COLDWASH: "Cold wash", 
    RINSESPIN: "Rinse + Spin", 
    KIDSWEAR: "Kidswear", 
    SCHOOLUNIFORM: "Schooluniform", 
    SWIMMINGWEAR: "Swimming wear", 
    RAINYSEASON: "Rain season", 
    GYMCLOTHES: "Gymclothes", 
    JEANS: "Jeans", 
    BLANKET: "Blanket", 
    SWEATSTAIN: "Sweat tain", 
    SINGLEGARMENT: "Single garment", 
    COLORPROTECTION: "Color protection", 
    NOISEMINIMIZE: "Noise minimize", 
    MINIMIZEWRINKLES: "Minimize wrinkles", 
    LIGHTLYSOILEDITEMS: "Lighty soild items", 
    MINIMIZEDETERGENT: "Minimize detergent", 
    SLEEVEHEMSANDCOLLARS: "Shirts and blouses", 
    JUICEANDFOODSTAINS: "Juice and foods tains", 
    QUICKTUBCLEAN: "Quick tub cleanup", 
    DRAIN: "Drain", 
    SPIN: "Spin",
    COTTON: "Cotton", 
    EASYCARE: "Easycare", 
    COTTONPLUS: "Cotton+", 
    DUVET: "Duvet", 
    MIXEDFABRIC: "Mix", 
    SPORTSWEAR: "Sportswear", 
    SILENTWASH: "Silent wash", 
    SPEED14: "14 Minutes", 
    TUB_CLEAN: "Tub cleanup", 
    WOOL: "Wool", 
    DELICATE: "Delicate", 
    ALLERGYSPASTEAM: "Allergy", 
    TURBO39: "39 Minutes",
    TURBO59: "59 Minutes",
    DRY: "Dry",
    DRY_COOLING: "Cooling",
    DRY_NORMAL: "Normal",
    DRY_IRON: "Iron",
    DRY_ECO: "ECO",
    DRY_SPEED: "Speed",
    DRY_LOW: "Lower",
    DRY_NORMAL_ECO: "Normal ECO",
    DRY_30: "Dryer time 30 Min.",
    DRY_60: "Dryer time 60 Min.",
    DRY_90: "Dryer time 90 Min.",
    DRY_120: "Dryer time 120 Min.",
    NO_SOILWASH: "Not soil",
    SOILWASH_TURBO_WASH: "Soil turbo wash",
    SOILWASH_TIMESAVE: "Soil time save",
    SOILWASH_NORMAL: "Normal soil",
    SOILWASH_INTENSIVE: "Intensive soil",
    NO_SPIN: "Spin off",
    SPIN_400: "400 RPM",
    SPIN_600: "600 RPM",
    SPIN_700: "700 RPM",
    SPIN_800: "800 RPM",
    SPIN_900: "900 RPM",
    SPIN_1000: "1000 RPM",
    SPIN_1100: "1100 RPM",
    SPIN_1200: "1200 RPM",
    SPIN_1400: "1400 RPM",
    SPIN_1600: "1600 RPM",
    SPIN_Max: "Spin Max",
    NOT_SELECTED: "No Selected",
    TEMP_COLD: "Cold",
    TEMP_20: "20°C",
    TEMP_30: "30°C",
    TEMP_40: "40°C",
    TEMP_50: "50°C",
    TEMP_60: "60°C",
    TEMP_95: "95°C",
    NO_TEMP: "No temperature",
    LOADITEM_OFF: "Loaditem off",
    LOADITEM_1: "Loaditem 1",
    LOADITEM_2: "Loaditem 2",
    LOADITEM_3: "Loaditem 3",
    TURBOWASH_OFF: "Turbo wash off",
    TURBOWASH_ON: "Turbo wash on",
    CREASECARE_OFF: "Crease care off",
    CREASECARE_ON: "Crease care on",
    STEAMSOFTENER_OFF: "Steam softener off",
    STEAMSOFTENER_ON: "Steam softener on",
    ECOHYBRID_OFF: "ECO off",
    ECOHYBRID_ON: "ECO on",
    MEDICRINSE_OFF: "Medic rinse off",
    MEDICRINSE_ON: "Medic rinse on",
    RINSE_SPIN_OFF: "Rinse and Spin off",
    RINSE_SPIN_ON: "Rinse and Spin on",
    PREWASH_OFF: "Prewash off",
    PREWASH_ON: "Prewash on",
    STEAM_OFF: "Steam off",
    STEAM_ON: "Steam on",
    INITIAL_BIT_OFF: "Weight detection off",
    INITIAL_BIT_ON: "Weight detection on",
    REMOTE_START_OFF: "Remote access off",
    REMOTE_START_ON: "Remote access on",
    DOOR_LOCK_OFF: "Door lock off",
    DOOR_LOCK_ON: "Door lock on",
    CHILDLOCK_OFF: "Child lock off",
    CHILDLOCK_ON: "Child lock on",
    NO_RINSE: "No rinse",
    RINSE_NORMAL: "Rinse normal", 
    RINSE_PLUS: "Rinse+", 
    RINSE_PLUSPLUS: "Rinse++",
    RINSE_NORMAL_HOLD: "Normal rinse",
    RINSE_PLUS_HOLD: "Normal rinse+",
    courseFL24inchBaseTitan: "Program", 
    smartCourseFL24inchBaseTitan: "Download Program",
    proofing: "Proofing",
    soilWash: "Soil wash",
    spin: "Spin",
    temp: "Temperature",
    rinse: "Rinse",
    reserveTimeHour: "Start time hour(s)",
    reserveTimeMinute: "Start time Minute(s)",
    loadItemWasher: "Load items", 
    turboWash: "Turbo wash",
    creaseCare: "Crease care",
    steamSoftener: "Steam softener",
    ecoHybrid: "ECO Hybrid",
    medicRinse: "Medic rinse",
    rinseSpin: "Rinse and Spin",
    preWash: "Prewash",
    steam: "Steam",
    initialBit: "Weight detection",
    remoteStart: "Remote access",
    doorLock: "Door lock",
    childLock: "Child lock",
    SEL_PROGRAM: "Select Program",
    MON_DEVICE: "Device Monitoring",
    FAVORITE: "Download favorite into the DP WMDownload.",
    LASTCOURSE: "The last 10 washes",
    STATISTIC: "Energy Statistic",
    PERIOD: "Period",
    HOURLY: "hourly",
    DAILY: "daily",
    MONTHLY: "monthly",
    YEARLY: "yearly",
    STARTDATE: "Start date in format YYYY.MM.DD",
    ENDDATE: "End date in format YYYY.MM.DD",
    JSONRESULT: "Result",
    SENDREQUEST: "Send request",
    NAMEFRIDGE: "Select request",
    F_DOOR: "Door open",
    F_ENERGY: "Energy",
    F_WATER: "Water consumption",
    F_ACTIVE: "Active power saving",
    F_FRIDGE: "Water fridge",
    F_SELFCARE: "Self care",
    antiCrease: "Anti-Crease",
    dampDryBeep: "Damp-Dry-Beep",
    dnnReady: "DNN Ready",
    dryLevel: "Dry-Level",
    handIron: "Hand-Iron",
    moreLessTime: "More / Less Time",
    reservation: "Reservation",
    selfClean: "Self-Clean",
    standby: "Standby",
    timeSetting: "Setting Time",
    ANTICREASE_OFF: "Anti-Crease off",
    ANTICREASE_ON: "Anti-Crease on",
    DAMPDRYBEEP_OFF: "Damp-Dry-Beep off",
    DAMPDRYBEEP_ON: "Damp-Dry-Beep on",
    DNNREADY_OFF: "DNN Ready off",
    DNNREADY_ON: "DNN Ready on",
    NO_DRYLEVEL: "No Dry-Level",
    DRYLEVEL_IRON: "Dry-Level-Iron",
    DRYLEVEL_CUPBOARD: "Dry-Level-Cupboard",
    DRYLEVEL_EXTRA: "Dry-Level-Extra",
    NO_ECOHYBRID: "Save Energy off",
    ECOHYBRID_ECO: "Save Energy",
    ECOHYBRID_NORMAL: "Normal",
    ECOHYBRID_TURBO: "Turbo",
    HANDIRON_OFF: "Hand-Iron off",
    HANDIRON_ON: "Hand-Iron on",
    RESERVATION_OFF: "Reservation off",
    RESERVATION_ON: "Reservation on",
    STANDBY_OFF: "Standby off",
    STANDBY_ON: "Standby on",
    SELFCLEAN_OFF: "Self-Clean off",
    SELFCLEAN_ON: "Self-Clean on",
    MON_UPDATE: "Last Update",
    SUPERDRY: "Superdry"
};
