"use strict";

const Json2iob = require("json2iob");

/**
 * Dishwasher handler device 204
 */
class Dishwasher {
    /**
     * @param {ioBroker.Adapter} iob iobroker wrapper
     */
    constructor(iob) {
        this.iob = iob;
        this.json2iob = new Json2iob(iob);
        this.states = {};
    }

    /**
     * @param {any} device
     * @param {any} deviceModel
     * @param {any} [constants]
     */
    async createRemote(device, deviceModel, constants) {
        const id = device.deviceId;
        if (!id || id == "") {
            this.iob.log.warn("Cannot found device id!");
            return;
        }
        // Not found snapshot.dishwasher.course
        // Not found snapshot.dishwasher.courseAutoDoor
        // Not found snapshot.dishwasher.courseType
        // Not found snapshot.dishwasher.smartCourse
        // Not found snapshot.dishwasher.smartMonVer
        // Not found snapshot.dishwasher.timeTrack
        // Not found snapshot.dishwasher.upContentsEndSoundNum

        if (deviceModel && deviceModel.Monitoring && deviceModel.Monitoring.protocol && deviceModel.Value) {
            for (const key in deviceModel.Monitoring.protocol) {
                const val = deviceModel.Monitoring.protocol[key];
                if (deviceModel.Value[val] && deviceModel.Value[val].value_mapping) {
                    this.states[key] = {};
                    for (const state in deviceModel.Value[val].value_mapping) {
                        const value = deviceModel.Value[val].value_mapping[state].replace("@", "");
                        if (state === "NONE" && value === "0") {
                            this.states[key][state] = value;
                        } else {
                            this.states[key][state] = value && constants[value] ? constants[value] : value;
                        }
                    }
                }
            }
        } else {
            this.iob.log.warn(
                `DeviceType 204 with platformType ${device.platformType} is not supported yet! Please create a issue!`,
            );
        }
        await this.iob.setObjectNotExistsAsync(`${id}.remote`, {
            type: "channel",
            common: {
                name: {
                    en: "Device remote control",
                    de: "Gerätefernsteuerung",
                    ru: "Дистанционное управление устройством",
                    pt: "Controle remoto do dispositivo",
                    nl: "Afstandsbediening van het apparaat",
                    fr: "télécommande de l'appareil",
                    it: "telecomando del dispositivo",
                    es: "Control remoto del dispositivo",
                    pl: "Zdalne sterowanie urządzeniem",
                    uk: "Дистанційне керування пристроєм",
                    "zh-cn": "设备遥控器",
                },
            },
            native: {},
        });
        if (deviceModel && deviceModel.ControlWifi) {
            if (deviceModel.ControlWifi.powerOff) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.powerOff`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Dishwasher turn off",
                            de: "Geschirrspüler ausschalten",
                            ru: "Выключите посудомоечную машину",
                            pt: "Desligar a máquina de lavar louça",
                            nl: "Vaatwasser uitschakelen",
                            fr: "Lave-vaisselle éteint",
                            it: "Spegnere la lavastoviglie",
                            es: "Apagar el lavavajillas",
                            pl: "Wyłączanie zmywarki",
                            uk: "Вимкнення посудомийної машини",
                            "zh-cn": "关闭洗碗机",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
            if (deviceModel.ControlWifi.powerOn) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.powerOn`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Dishwasher turn on",
                            de: "Geschirrspüler einschalten",
                            ru: "Включите посудомоечную машину",
                            pt: "Ligar a máquina de lavar louça",
                            nl: "Vaatwasser inschakelen",
                            fr: "Lave-vaisselle allumé",
                            it: "Accendere la lavastoviglie",
                            es: "Encienda el lavavajillas",
                            pl: "Włącz zmywarkę",
                            uk: "Увімкнення посудомийної машини",
                            "zh-cn": "洗碗机开启",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
            if (deviceModel.ControlWifi.cancelCourse) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.cancelCourse`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Cancel program",
                            de: "Programm abbrechen",
                            ru: "Отменить программу",
                            pt: "Cancelar programa",
                            nl: "Programma annuleren",
                            fr: "Annuler le programme",
                            it: "Annulla programma",
                            es: "Cancelar programa",
                            pl: "Anuluj program",
                            uk: "Скасувати програму",
                            "zh-cn": "取消程序",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
            if (deviceModel.ControlWifi.pauseCourse) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.pauseCourse`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Pause program",
                            de: "Programm pausieren",
                            ru: "Приостановить программу",
                            pt: "Pausar programa",
                            nl: "Programma pauzeren",
                            fr: "Programme en pause",
                            it: "Metti in pausa il programma",
                            es: "Pausar programa",
                            pl: "Wstrzymaj program",
                            uk: "Призупинити програму",
                            "zh-cn": "暂停程序",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
            if (deviceModel.ControlWifi.resumeCourse) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.resumeCourse`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Wash program resume",
                            de: "Wiederaufnahme des Waschprogramms",
                            ru: "Программа стирки возобновляется",
                            pt: "Resumo do programa Wash",
                            nl: "Wasprogramma hervat",
                            fr: "Reprise du programme de lavage",
                            it: "Riepilogo del programma di lavaggio",
                            es: "Reanudación del programa de lavado",
                            pl: "CV programu mycia",
                            uk: "Відновлення програми прання",
                            "zh-cn": "洗涤程序恢复",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
            if (deviceModel.ControlWifi.AirFilterInit) {
                await this.iob.setObjectNotExistsAsync(`${id}.remote.airFilterInit`, {
                    type: "state",
                    common: {
                        name: {
                            en: "Air filter initialized",
                            de: "Luftfilter initialisiert",
                            ru: "Воздушный фильтр инициализирован",
                            pt: "Filtro de ar inicializado",
                            nl: "Luchtfilter geïnitialiseerd",
                            fr: "Filtre à air initialisé",
                            it: "Filtro dell'aria inizializzato",
                            es: "Filtro de aire inicializado",
                            pl: "Filtr powietrza zainicjowany",
                            uk: "Повітряний фільтр ініціалізовано",
                            "zh-cn": "空气过滤器已初始化",
                        },
                        type: "boolean",
                        role: "button",
                        write: true,
                        read: false,
                        def: false,
                    },
                    native: {},
                });
            }
        } else {
            this.iob.log.warn(`${id}: Cannaot found controlwifi keys!`);
        }
    }

    /**
     * @param {any} element
     */
    async createDevice(element) {
        const cleanup = this.removeNull(element);
        await this.json2iob.parse(element.deviceId, cleanup, {
            channelName: {
                name: element.alias ? element.alias : "Dishwasher",
            },
            descriptions: this.objectName(),
            forceIndex: true,
            units: this.objectUnit(),
            states: this.states,
            min: this.objectMin(),
            max: this.objectMax(),
        });
    }

    /**
     * @param {string} devicedp
     */
    async createSendJson(devicedp) {
        await this.iob.setObjectNotExistsAsync(`${devicedp}.remote.sendJSON`, {
            type: "state",
            common: {
                name: "sendJSON",
                type: "string",
                write: true,
                read: true,
                role: "json",
                desc: "sendJSON",
                def: "",
            },
            native: {},
        });
        await this.iob.setObjectNotExistsAsync(`${devicedp}.remote.sendJSONNoSync`, {
            type: "state",
            common: {
                name: "sendJSONNoSync",
                type: "string",
                write: true,
                read: true,
                role: "json",
                desc: "sendJSONNoSync",
                def: "",
            },
            native: {},
        });
    }

    /**
     * @param {any} obj
     */
    removeNull(obj) {
        return JSON.parse(JSON.stringify(obj), (key, value) => {
            if (value === null) {
                return undefined;
            }
            return value;
        });
    }

    /**
     * Object minimum
     */
    objectMin() {
        return {
            initialTimeMinute: 0,
            remainTimeHour: 0,
            remainTimeMinute: 0,
            initialTimeHour: 0,
            reserveTimeMinute: 0,
            reserveTimeHour: 0,
        };
    }

    /**
     * Object maximum
     */
    objectMax() {
        return {
            initialTimeMinute: 59,
            remainTimeHour: 6,
            remainTimeMinute: 59,
            initialTimeHour: 6,
            reserveTimeMinute: 59,
            reserveTimeHour: 6,
        };
    }

    /**
     * Object units
     */
    objectUnit() {
        return {
            filterRemainPercent: "%",
            initialTimeMinute: "min",
            remainTimeHour: "h",
            remainTimeMinute: "min",
            initialTimeHour: "h",
            reserveTimeMinute: "min",
            reserveTimeHour: "h",
        };
    }

    /**
     * Object name
     */
    objectName() {
        return {
            state: {
                en: "State",
                de: "Zustand",
                ru: "Состояние",
                pt: "Estado",
                nl: "Staat",
                fr: "État",
                it: "Stato",
                es: "Estado",
                pl: "Państwo",
                uk: "Штат",
                "zh-cn": "状态",
            },
            process: {
                en: "Process",
                de: "Verfahren",
                ru: "Процесс",
                pt: "Processo",
                nl: "Proces",
                fr: "Processus",
                it: "Processo",
                es: "Proceso",
                pl: "Proces",
                uk: "Процес",
                "zh-cn": "过程",
            },
            error: {
                en: "Error",
                de: "Fehler",
                ru: "Ошибка",
                pt: "Erro",
                nl: "Fout",
                fr: "Erreur",
                it: "Errore",
                es: "Error",
                pl: "Błąd",
                uk: "Помилка",
                "zh-cn": "错误",
            },
            initialTimeHour: {
                en: "Initial time (hour)",
                de: "Anfangszeit (Stunde)",
                ru: "Начальное время (час)",
                pt: "Hora inicial (hora)",
                nl: "Begintijd (uur)",
                fr: "Heure initiale (heure)",
                it: "Tempo iniziale (ore)",
                es: "Hora inicial (hora)",
                pl: "Czas początkowy (godzina)",
                uk: "Початковий час (година)",
                "zh-cn": "初始时间（小时）",
            },
            initialTimeMinute: {
                en: "Initial time (minute)",
                de: "Anfangszeit (Minute)",
                ru: "Начальное время (минуты)",
                pt: "Tempo inicial (minutos)",
                nl: "Begintijd (minuut)",
                fr: "Heure initiale (minute)",
                it: "Tempo iniziale (minuti)",
                es: "Tiempo inicial (minutos)",
                pl: "Czas początkowy (minuta)",
                uk: "Початковий час (хвилина)",
                "zh-cn": "初始时间（分钟）",
            },
            course: {
                en: "Wash course",
                de: "Waschgang",
                ru: "Курс стирки",
                pt: "Curso de lavagem",
                nl: "Wascursus",
                fr: "Cours de lavage",
                it: "Corso di lavaggio",
                es: "Curso de lavado",
                pl: "Kurs mycia",
                uk: "Курс прання",
                "zh-cn": "洗涤通道",
            },
            courseType: {
                en: "Wash course type",
                de: "Waschgangart",
                ru: "Тип стирки",
                pt: "Tipo de curso de lavagem",
                nl: "Wascursustype",
                fr: "Type de cours de lavage",
                it: "Tipo di corso di lavaggio",
                es: "Tipo de curso de lavado",
                pl: "Typ kursu mycia",
                uk: "Тип циклу прання",
                "zh-cn": "洗涤课程类型",
            },
            remainTimeHour: {
                en: "Remain time (hour)",
                de: "Restzeit (Stunde)",
                ru: "Осталось времени (часы)",
                pt: "Tempo restante (horas)",
                nl: "Resterende tijd (uur)",
                fr: "Temps restant (heure)",
                it: "Tempo rimanente (ore)",
                es: "Tiempo restante (horas)",
                pl: "Pozostały czas (godzina)",
                uk: "Час, що залишився (година)",
                "zh-cn": "剩余时间（小时）",
            },
            remainTimeMinute: {
                en: "Remain time (minute)",
                de: "Verbleibende Zeit (Minuten)",
                ru: "Осталось времени (минуты)",
                pt: "Tempo restante (minutos)",
                nl: "Resterende tijd (minuut)",
                fr: "Temps restant (minute)",
                it: "Tempo rimanente (minuti)",
                es: "Tiempo restante (minutos)",
                pl: "Pozostały czas (minuty)",
                uk: "Час, що залишився (хвилини)",
                "zh-cn": "剩余时间（分钟）",
            },
            reserveTimeHour: {
                en: "Reserve time (hour)",
                de: "Wartezeit (Stunde)",
                ru: "Время резервирования (часы)",
                pt: "Tempo de reserva (hora)",
                nl: "Reserveer tijd (uur)",
                fr: "Réserver du temps (heure)",
                it: "Tempo di riserva (ore)",
                es: "Tiempo de reserva (hora)",
                pl: "Czas rezerwowy (godzina)",
                uk: "Резервний час (година)",
                "zh-cn": "预留时间（小时）",
            },
            reserveTimeMinute: {
                en: "Reserve time (minute)",
                de: "Wartezeit (Minuten)",
                ru: "Время резервирования (минуты)",
                pt: "Tempo de reserva (minutos)",
                nl: "Reserveer tijd (minuut)",
                fr: "Réserver du temps (minute)",
                it: "Tempo di riserva (minuti)",
                es: "Tiempo de reserva (minutos)",
                pl: "Czas rezerwowy (minuta)",
                uk: "Резервний час (хвилина)",
                "zh-cn": "预留时间（分钟）",
            },
            childLock: {
                en: "Child lock",
                de: "Kindersicherung",
                ru: "блокировка от детей",
                pt: "Trava de segurança para crianças",
                nl: "Kinderslot",
                fr: "Verrouillage enfant",
                it: "Blocco di sicurezza per bambini",
                es: "Bloqueo para niños",
                pl: "Blokada dziecięca",
                uk: "Блокування від дітей",
                "zh-cn": "儿童锁",
            },
            door: {
                en: "Door state",
                de: "Türzustand",
                ru: "Состояние двери",
                pt: "Estado da porta",
                nl: "Deur staat",
                fr: "État de la porte",
                it: "Stato della porta",
                es: "Estado de la puerta",
                pl: "Stan drzwi",
                uk: "Стан дверей",
                "zh-cn": "门州",
            },
            rinseRefill: {
                en: "dish soap refill",
                de: "Spülmittel nachfüllen",
                ru: "заправка для мыла для посуды",
                pt: "refil de sabonete",
                nl: "navulling voor afwasmiddel",
                fr: "recharge de savon",
                it: "ricarica detersivo",
                es: "recambio de jabón",
                pl: "wkład do mydła do naczyń",
                uk: "Заправка мила для посуду",
                "zh-cn": "洗洁精补充装",
            },
            saltRefill: {
                en: "Salt refill",
                de: "Salz nachfüllen",
                ru: "Пополнение запасов соли",
                pt: "Reposição de sal",
                nl: "Zoutvulling",
                fr: "Recharge de sel",
                it: "Rifornimento di sale",
                es: "Recarga de sal",
                pl: "Uzupełnienie soli",
                uk: "Поповнення солі",
                "zh-cn": "补充盐",
            },
            signalLevel: {
                en: "Signal Level",
                de: "Signalpegel",
                ru: "Уровень сигнала",
                pt: "Nível do sinal",
                nl: "Signaalniveau",
                fr: "Signal Level",
                it: "Segnale",
                es: "Nivel de señal",
                pl: "Poziom sygnału",
                uk: "Рівень сигналу",
                "zh-cn": "信号等级",
            },
            mcReminderSetting: {
                en: "MC reminder setting",
                de: "MC-Erinnerungseinstellung",
                ru: "настройка напоминания MC",
                pt: "Configuração de lembrete MC",
                nl: "MC-herinneringsinstelling",
                fr: "Réglage du rappel MC",
                it: "Impostazione promemoria MC",
                es: "Configuración de recordatorio MC",
                pl: "Ustawienie przypomnienia MC",
                uk: "Налаштування нагадування MC",
                "zh-cn": "MC提醒设置",
            },
            cleanLReminder: {
                en: "Light cleansing reminder",
                de: "Lichtreinigungserinnerung",
                ru: "Светоочистительное напоминание",
                pt: "Aviso de limpeza de luz",
                nl: "Lichtreinigingsherinnering",
                fr: "Rappel au nettoyage de la lumière",
                it: "Promemoria di pulizia della luce",
                es: "Memoria de limpieza de luz",
                pl: "Przypominanie o oczyszczaniu światła",
                uk: "Світло очищає нагадування",
                "zh-cn": "轻清理提醒",
            },
            timeIndicator: {
                en: "Time Indicator",
                de: "Zeitanzeiger",
                ru: "Показатель времени",
                pt: "Indicador de hora",
                nl: "Tijdindicator",
                fr: "Indicateur de temps",
                it: "Indicatore del tempo",
                es: "Indicador de tiempo",
                pl: "Wskaźnik czasu",
                uk: "Індикатор часу",
                "zh-cn": "时间指标",
            },
            nightDry: {
                en: "Night Dry",
                de: "Nachttrocken",
                ru: "Ночная сухость",
                pt: "Seco noturno",
                nl: "Nacht droog",
                fr: "Séchage nocturne",
                it: "Notte secca",
                es: "Noche seca",
                pl: "Noc sucha",
                uk: "Нічний суха",
                "zh-cn": "夜间干燥",
            },
            delayStart: {
                en: "Delay Start",
                de: "Verzögerter Start",
                ru: "Задержка старта",
                pt: "Início atrasado",
                nl: "Vertraagde start",
                fr: "Démarrage différé",
                it: "Avvio ritardato",
                es: "Inicio retardado",
                pl: "Opóźniony start",
                uk: "Відкладений старт",
                "zh-cn": "延迟启动",
            },
            energySaver: {
                en: "Energy Saver",
                de: "Energiesparer",
                ru: "Энергосбережение",
                pt: "Economizador de energia",
                nl: "Energiebesparing",
                fr: "Économiseur d'énergie",
                it: "Risparmio energetico",
                es: "Ahorro de energía",
                pl: "Oszczędność energii",
                uk: "Енергозбереження",
                "zh-cn": "节能器",
            },
            extraDry: {
                en: "Extra Dry",
                de: "Extra trocken",
                ru: "Экстрасухой",
                pt: "Extra seco",
                nl: "Extra droog",
                fr: "Extra sec",
                it: "Extra Dry",
                es: "Extra seco",
                pl: "Extra Dry",
                uk: "Екстра сухий",
                "zh-cn": "特干",
            },
            highTemp: {
                en: "High Temperature",
                de: "Hohe Temperatur",
                ru: "Высокая температура",
                pt: "Alta temperatura",
                nl: "Hoge temperatuur",
                fr: "Haute température",
                it: "Alta temperatura",
                es: "Temperatura alta",
                pl: "Wysoka temperatura",
                uk: "Висока температура",
                "zh-cn": "高温",
            },
            dualZone: {
                en: "Dual zone",
                de: "Doppelzone",
                ru: "Двухзонный",
                pt: "Zona dupla",
                nl: "Dubbele zone",
                fr: "Zone double",
                it: "Zona doppia",
                es: "Zona doble",
                pl: "Podwójna strefa",
                uk: "Подвійна зона",
                "zh-cn": "双区",
            },
            halfLoad: {
                en: "Half load",
                de: "Halbe Ladung",
                ru: "Половина загрузки",
                pt: "Meia carga",
                nl: "Halve lading",
                fr: "demi-charge",
                it: "Mezzo carico",
                es: "Media carga",
                pl: "Połowa ładunku",
                uk: "Половинне завантаження",
                "zh-cn": "半载",
            },
            autoDoor: {
                en: "Automatic open door",
                de: "Automatische Türöffnung",
                ru: "Автоматическое открытие двери",
                pt: "Porta automática de abertura",
                nl: "Automatische deuropener",
                fr: "porte à ouverture automatique",
                it: "Apertura automatica della porta",
                es: "Puerta de apertura automática",
                pl: "Automatyczne otwieranie drzwi",
                uk: "Автоматичні двері",
                "zh-cn": "自动开门",
            },
            steam: {
                en: "Steam",
                de: "Dampf",
                ru: "Пар",
                pt: "Vapor",
                nl: "Stoom",
                fr: "Vapeur",
                it: "Vapore",
                es: "Vapor",
                pl: "Para",
                uk: "Пара",
                "zh-cn": "蒸汽",
            },
            rinseLevel: {
                en: "Rinse level",
                de: "Spülniveau",
                ru: "Уровень ополаскивания",
                pt: "Nível de enxágue",
                nl: "Spoelniveau",
                fr: "Niveau de rinçage",
                it: "Livello di risciacquo",
                es: "Nivel de enjuague",
                pl: "Poziom płukania",
                uk: "Рівень полоскання",
                "zh-cn": "冲洗液位",
            },
            softeningLevel: {
                en: "Softening Level",
                de: "Erweichungsgrad",
                ru: "Уровень смягчения",
                pt: "Nível de amolecimento",
                nl: "Verzachtingsniveau",
                fr: "Niveau d'adoucissement",
                it: "Livello di rammollimento",
                es: "Nivel de suavizado",
                pl: "Poziom zmiękczenia",
                uk: "Рівень пом'якшення",
                "zh-cn": "软化程度",
            },
            smartCourse: {
                en: "Smart wash course",
                de: "Smart-Waschprogramm",
                ru: "Курс умной стирки",
                pt: "Curso de lavagem inteligente",
                nl: "Slimme wascursus",
                fr: "Cours de lavage intelligent",
                it: "Corso di lavaggio intelligente",
                es: "Curso de lavado inteligente",
                pl: "Kurs inteligentnego mycia",
                uk: "Курс розумного прання",
                "zh-cn": "智能清洗课程",
            },
            currentDownloadCourse: {
                en: "Current download wash course",
                de: "Aktueller Download-Waschkurs",
                ru: "Текущая загрузка курса стирки",
                pt: "Curso de lavagem de download atual",
                nl: "Huidige download wascursus",
                fr: "Cours de lavage en téléchargement actuel",
                it: "Corso di lavaggio scaricabile attuale",
                es: "Curso de lavado de descarga actual",
                pl: "Aktualny kurs mycia do pobrania",
                uk: "Поточний курс прання для завантаження",
                "zh-cn": "当前下载洗涤课程",
            },
            downloadCourseSlot1: {
                en: "Download Wash Course Slot 1",
                de: "Waschkurs herunterladen, Slot 1",
                ru: "Скачать курс стирки, слот 1",
                pt: "Baixe o Curso Wash Slot 1",
                nl: "Download cursusdeelname 1",
                fr: "Télécharger le créneau horaire 1 du cours Wash",
                it: "Scarica lo slot 1 del corso di lavaggio",
                es: "Descargar Curso de Lavado Ranura 1",
                pl: "Pobierz kurs Wash Slot 1",
                uk: "Завантажити курс прання, слот 1",
                "zh-cn": "下载洗涤课程第 1 节",
            },
            downloadCourseSlot2: {
                en: "Download Wash Course, Slot 2",
                de: "Waschkurs herunterladen, Slot 2",
                ru: "Скачать курс по стирке, слот 2",
                pt: "Baixe o curso Wash, Slot 2",
                nl: "Download de wascursus, deel 2",
                fr: "Télécharger le cours Wash, créneau 2",
                it: "Scarica il corso di lavaggio, slot 2",
                es: "Descargar Curso de Lavado, Ranura 2",
                pl: "Pobierz kurs Wash, slot 2",
                uk: "Завантажити курс прання, слот 2",
                "zh-cn": "下载洗涤课程，第二节",
            },
            downloadCourseSlot3: {
                en: "Download Wash Course, Slot 3",
                de: "Waschkurs herunterladen, Slot 3",
                ru: "Скачать курс по стирке, слот 3",
                pt: "Baixe o curso Wash, Slot 3.",
                nl: "Download de wascursus, slot 3",
                fr: "Télécharger le cours Wash, emplacement 3",
                it: "Scarica il corso di lavaggio, slot 3",
                es: "Descargar Curso de Lavado, Ranura 3",
                pl: "Pobierz kurs Wash, slot 3",
                uk: "Завантажити курс прання, слот 3",
                "zh-cn": "下载洗涤课程，第 3 节",
            },
            slotNumDownloadCourse: {
                en: "Slot number for the download wash program",
                de: "Slot für das Download-Waschprogramm",
                ru: "Номер слота для загрузки программы стирки",
                pt: "Número do slot para baixar o programa",
                nl: "Sleufnummer voor het wasprogramma om te downloaden",
                fr: "Numéro d'emplacement du programme Download Wash",
                it: "Slot per il download del programma Wash",
                es: "Número de ranura del programa Download Wash",
                pl: "Numer gniazda programu do prania do pobrania",
                uk: "Номер слота для завантаження програми прання",
                "zh-cn": "下载清洗程序的插槽号",
            },
            tclCount: {
                en: "Tcl count",
                de: "Tcl-Zahl",
                ru: "Количество Tcl",
                pt: "N° Tcl",
                nl: "Tcl-aantal",
                fr: "compte TCL",
                it: "Cod. Tcl",
                es: "Recuento Tcl",
                pl: "Ilość Tcl",
                uk: "Підрахунок Tcl",
                "zh-cn": "Tcl 计数",
            },
            extraRinse: {
                en: "Extra Rinse",
                de: "Extra spülen",
                ru: "Дополнительное полоскание",
                pt: "Extra Lave",
                nl: "Extra spoeling",
                fr: "Extra Rinse",
                it: "Extra Rinse",
                es: "Extra Rinse",
                pl: "Dodatkowe płukanie",
                uk: "Додаткове полоскання",
                "zh-cn": "额外冲洗",
            },
            extraRinseLevel: {
                en: "Extra Rinse Level",
                de: "Extra Spülstufe",
                ru: "Дополнительный уровень полоскания",
                pt: "Enxágue extra",
                nl: "Extra spoelniveau",
                fr: "Niveau de rinçage élevé",
                it: "Extra Rinse Level",
                es: "Nivel de enjuague extra",
                pl: "Dodatkowy poziom płukania",
                uk: "Додатковий рівень полоскання",
                "zh-cn": "额外冲洗等级",
            },
            remoteStart: {
                en: "RemoteStart",
                de: "Fernstart",
                ru: "Дистанционный запуск",
                pt: "Início remoto",
                nl: "Starten op afstand",
                fr: "RemoteStart",
                it: "Avvio remoto",
                es: "RemoteStart",
                pl: "Zdalny start",
                uk: "Віддалений запуск",
                "zh-cn": "远程启动",
            },
            coolDry: {
                en: "Cool dry",
                de: "Kühl trocken",
                ru: "Прохладная сушка",
                pt: "Seco",
                nl: "Koel en droog",
                fr: "Cool et sec",
                it: "Cool dry",
                es: "Frío y seco",
                pl: "Chłodnie na sucho",
                uk: "Прохолодно сухо",
                "zh-cn": "凉爽干燥",
            },
            heatDry: {
                en: "Heat dry",
                de: "Hitzetrocknen",
                ru: "Термическая сушка",
                pt: "Secar",
                nl: "Met hitte drogen",
                fr: "Sécher à chaud",
                it: "Heat dry",
                es: "Secar al calor",
                pl: "Ciepło na sucho",
                uk: "Тепло сушіть",
                "zh-cn": "加热干燥",
            },
            endAlarmSound: {
                en: "End Alarm Sound",
                de: "Alarmton beenden",
                ru: "Завершить звук будильника",
                pt: "Som End Alarm",
                nl: "Alarmgeluid beëindigen",
                fr: "Fin de l'alarme",
                it: "End Alarm Sound",
                es: "Finalizar alarma",
                pl: "Zakończ dźwięk alarmu",
                uk: "Завершення звуку тривоги",
                "zh-cn": "结束警报声",
            },
            buzzerLevel: {
                en: "Buzzer Level",
                de: "Buzzer-Pegel",
                ru: "Уровень зуммера",
                pt: "Nível da campainha",
                nl: "Zoemerniveau",
                fr: "Buzzer Level",
                it: "Buzzer Level",
                es: "Nivel de timbre",
                pl: "Poziom brzęczyka",
                uk: "Рівень зумера",
                "zh-cn": "蜂鸣器音量",
            },
            keepDish: {
                en: "Keep remote start",
                de: "Fernstart beibehalten",
                ru: "Сохраните дистанционный запуск",
                pt: "Mantenha o arranque remoto",
                nl: "Afstandsbediening voor starten behouden",
                fr: "Conserver le démarrage à distance",
                it: "Mantieni l'avvio remoto",
                es: "Mantener el arranque remoto",
                pl: "Zachowaj zdalny start",
                uk: "Зберегти дистанційний запуск",
                "zh-cn": "保持远程启动",
            },
            autoSelect: {
                en: "Automatic select",
                de: "Automatische Auswahl",
                ru: "Автоматический выбор",
                pt: "Seleção automática",
                nl: "Automatische selectie",
                fr: "Sélection automatique",
                it: "Selezione automatica",
                es: "Selección automática",
                pl: "Automatyczny wybór",
                uk: "Автоматичний вибір",
                "zh-cn": "自动选择",
            },
            airFilter: {
                en: "Air Filter",
                de: "Luftfilter",
                ru: "Воздушный фильтр",
                pt: "Filtro de ar",
                nl: "Luchtfilter",
                fr: "Filtre à air",
                it: "Filtro dell'aria",
                es: "Filtro de aire",
                pl: "Filtr powietrza",
                uk: "Повітряний фільтр",
                "zh-cn": "空气过滤器",
            },
            filterRemainPercent: {
                en: "Filter remain percent",
                de: "Filter verbleibender Prozentsatz",
                ru: "Остаток фильтра в процентах",
                pt: "Filtrar porcentagem restante",
                nl: "Filter resterend percentage",
                fr: "Pourcentage restant du filtre",
                it: "Percentuale rimanente del filtro",
                es: "Porcentaje de filtro restante",
                pl: "Pozostały procent filtra",
                uk: "Відсоток залишку фільтра",
                "zh-cn": "过滤器剩余百分比",
            },
            isPauseEnable: {
                en: "Is pause enable",
                de: "Ist die Pause aktiviert?",
                ru: "Включена ли пауза?",
                pt: "A opção de pausa está habilitada?",
                nl: "Is pauze inschakelen mogelijk?",
                fr: "La pause est-elle activée ?",
                it: "La pausa è abilitata?",
                es: "¿Está habilitada la pausa?",
                pl: "Czy pauza jest włączona?",
                uk: "Чи ввімкнено паузу",
                "zh-cn": "是否启用暂停功能",
            },
            upContentsEndSoundNum: {
                en: "Up contents for end time sound",
                de: "Inhalte für Endzeit-Sound",
                ru: "Содержание для звука конца времен",
                pt: "Conteúdo para som de término de tempo",
                nl: "Inhoud voor eindtijdgeluid",
                fr: "Contenu en haut pour le son de la fin des temps",
                it: "Contenuti per il suono di fine tempo",
                es: "Contenido para el sonido del fin de los tiempos",
                pl: "Zawartość dla dźwięku końca czasów",
                uk: "Зміст для звуку кінця часу",
                "zh-cn": "末日之声的内容",
            },
            lowNoise: {
                en: "Low Noise",
                de: "Geräuscharm",
                ru: "Низкий уровень шума",
                pt: "Baixo ruído",
                nl: "Laag geluidsniveau",
                fr: "Faible bruit",
                it: "Basso rumore",
                es: "Bajo nivel de ruido",
                pl: "Niski poziom hałasu",
                uk: "Низький рівень шуму",
                "zh-cn": "低噪音",
            },
            remoteStartMode: {
                en: "Remote Start Mode",
                de: "Fernstartmodus",
                ru: "Режим дистанционного запуска",
                pt: "Modo de inicialização remota",
                nl: "Startmodus op afstand",
                fr: "Mode de démarrage à distance",
                it: "Modalità di avviamento remoto",
                es: "Modo de arranque remoto",
                pl: "Tryb zdalnego uruchamiania",
                uk: "Режим дистанційного запуску",
                "zh-cn": "远程启动模式",
            },
            speakerLevel: {
                en: "Speaker Level",
                de: "Lautsprecherpegel",
                ru: "Уровень громкости динамика",
                pt: "Nível do orador",
                nl: "Luidsprekerniveau",
                fr: "Niveau du haut-parleur",
                it: "Livello degli altoparlanti",
                es: "Nivel del altavoz",
                pl: "Poziom głośnika",
                uk: "Рівень гучномовця",
                "zh-cn": "扬声器级别",
            },
            coolDryTime: {
                en: "Cool dry time",
                de: "Kühle Trockenzeit",
                ru: "Время сушки в прохладном месте",
                pt: "Tempo de secagem fresco",
                nl: "Koel droogtijd",
                fr: "temps de séchage à froid",
                it: "Tempo di asciugatura a freddo",
                es: "Tiempo fresco y seco",
                pl: "Czas schnięcia w chłodnym miejscu",
                uk: "Прохолодний сухий час",
                "zh-cn": "凉爽干燥时期",
            },
            timeIndicatorBrightnessLevel: {
                en: "Time indicator brightness level",
                de: "Helligkeitsstufe der Zeitanzeige",
                ru: "уровень яркости индикатора времени",
                pt: "Nível de brilho do indicador de tempo",
                nl: "helderheidsniveau van de tijdindicator",
                fr: "niveau de luminosité de l'indicateur horaire",
                it: "Livello di luminosità dell'indicatore orario",
                es: "Nivel de brillo del indicador de hora",
                pl: "Poziom jasności wskaźnika czasu",
                uk: "Рівень яскравості індикатора часу",
                "zh-cn": "时间指示器亮度级别",
            },
            insideBrightnessLevel: {
                en: "Inside brightness level",
                de: "Innenhelligkeit",
                ru: "Внутренний уровень яркости",
                pt: "Nível de brilho interno",
                nl: "Binnenste helderheidsniveau",
                fr: "Niveau de luminosité intérieure",
                it: "Livello di luminosità interna",
                es: "Nivel de brillo interior",
                pl: "Poziom jasności wewnątrz",
                uk: "Рівень яскравості всередині",
                "zh-cn": "室内亮度级别",
            },
            voiceGuideLevel: {
                en: "Voice guide level",
                de: "Sprachführungspegel",
                ru: "Уровень голосового руководства",
                pt: "Nível de guia de voz",
                nl: "Stembegeleidingsniveau",
                fr: "Niveau du guide vocal",
                it: "Livello della guida vocale",
                es: "Nivel de guía por voz",
                pl: "Poziom przewodnika głosowego",
                uk: "Рівень голосового підказки",
                "zh-cn": "语音指南级别",
            },
            totalSound: {
                en: "Total sound",
                de: "Totaler Sound",
                ru: "Полный звук",
                pt: "Som total",
                nl: "Totaal geluid",
                fr: "Son total",
                it: "Suono totale",
                es: "Sonido total",
                pl: "Całkowity dźwięk",
                uk: "Загальний звук",
                "zh-cn": "总声音",
            },
            beforeWashLv: {
                en: "Before Wash level",
                de: "Vor Waschstufe",
                ru: "Уровень до стирки",
                pt: "Antes de lavar",
                nl: "Niveau voor het wassen",
                fr: "Niveau avant lavage",
                it: "Prima del lavaggio",
                es: "Nivel antes de lavado",
                pl: "Poziom przed praniem",
                uk: "Рівень перед пранням",
                "zh-cn": "洗涤前等级",
            },
            beforeDryLv: {
                en: "Before Dry level",
                de: "Vor Trockenstufe",
                ru: "Уровень «До высыхания»",
                pt: "Antes de secar",
                nl: "Niveau vóór het drogen",
                fr: "Avant le niveau sec",
                it: "Prima di Dry",
                es: "Antes de Dry Level",
                pl: "Przed poziomem suchym",
                uk: "Перед рівнем сухого",
                "zh-cn": "在干燥水平之前",
            },
            beforeNoiseLv: {
                en: "Before Noise level",
                de: "Vor Lärmpegel",
                ru: "До уровня шума",
                pt: "Antes do ruído",
                nl: "Voor het geluidsniveau",
                fr: "Avant le niveau sonore",
                it: "Prima del rumore",
                es: "Antes del nivel de ruido",
                pl: "Przed poziomem hałasu",
                uk: "До рівня шуму",
                "zh-cn": "噪音水平之前",
            },
            beforeEnergy: {
                en: "Before energy",
                de: "Vor Energie",
                ru: "До энергии",
                pt: "Antes da energia",
                nl: "Voor energie",
                fr: "Avant l'énergie",
                it: "Prima Energy",
                es: "Antes de la energía",
                pl: "Przed energią",
                uk: "Перед енергією",
                "zh-cn": "在能量之前",
            },
            beforeTime: {
                en: "Before time",
                de: "Vor der Zeit",
                ru: "До начала времени",
                pt: "Antes",
                nl: "Voor de tijd",
                fr: "Avant l'heure",
                it: "Prima",
                es: "Antes de hora",
                pl: "Przed czasem",
                uk: "До часу",
                "zh-cn": "在时间之前",
            },
            isBeforeFinish: {
                en: "Is before finish",
                de: "Ist vor Ende",
                ru: "Находится до финиша",
                pt: "É antes do fim",
                nl: "Is voor het einde",
                fr: "C'est avant la fin",
                it: "È prima di finire",
                es: "Es antes de acabar",
                pl: "Jest przed końcem",
                uk: "Є перед фінішем",
                "zh-cn": "在完成之前",
            },
            changeWashLv: {
                en: "Change Wash Level",
                de: "Waschstufe ändern",
                ru: "Изменить уровень стирки",
                pt: "Mude o nível de lavagem",
                nl: "Wasniveau wijzigen",
                fr: "Changer le niveau de lavage",
                it: "Cambia Wash Level",
                es: "Cambiar nivel de lavado",
                pl: "Zmień poziom prania",
                uk: "Зміна рівня прання",
                "zh-cn": "更改洗涤级别",
            },
            changeDryLv: {
                en: "Change Dry Level",
                de: "Trockenstufe ändern",
                ru: "Измените уровень сухости",
                pt: "Mude o nível seco",
                nl: "Droogniveau wijzigen",
                fr: "Changer le niveau sec",
                it: "Cambia Dry Level",
                es: "Cambiar nivel seco",
                pl: "Zmień poziom suchego",
                uk: "Змініть рівень сухого",
                "zh-cn": "更改干燥等级",
            },
            changeNoiseLv: {
                en: "Change Noise Level",
                de: "Lärmpegel ändern",
                ru: "Изменить уровень шума",
                pt: "Mudar o nível de ruído",
                nl: "Geluidsniveau wijzigen",
                fr: "Changer le niveau sonore",
                it: "Cambia rumore",
                es: "Cambiar nivel de ruido",
                pl: "Zmień poziom hałasu",
                uk: "Зміна рівня шуму",
                "zh-cn": "更改噪音等级",
            },
            changeEnergy: {
                en: "Change energy",
                de: "Energie ändern",
                ru: "Измените энергию",
                pt: "Mude energia",
                nl: "Energie veranderen",
                fr: "Change energy",
                it: "Cambia energia",
                es: "Cambiar energía",
                pl: "Zmień energię",
                uk: "Змініть енергію",
                "zh-cn": "改变能量",
            },
            changeTime: {
                en: "Change time",
                de: "Zeit ändern",
                ru: "Время смены",
                pt: "Mude a hora",
                nl: "Verander de tijd",
                fr: "Changez d'heure",
                it: "Cambia ora",
                es: "Cambiar hora",
                pl: "Zmień czas",
                uk: "Змінити час",
                "zh-cn": "更改时间",
            },
            isChangeFinish: {
                en: "Is change finish",
                de: "Ist die Änderung abgeschlossen?",
                ru: "Изменение отделки",
                pt: "A mudança acabou",
                nl: "Is de verandering voltooid?",
                fr: "Le changement est-il terminé ?",
                it: "Il cambiamento è finito",
                es: "¿El cambio ha terminado?",
                pl: "Czy zmiana się zakończyła?",
                uk: "Чи зміни завершені?",
                "zh-cn": "变更结束了吗？",
            },
            checkWashLv: {
                en: "Check Wash Level",
                de: "Waschwasserstand prüfen",
                ru: "Проверьте уровень воды во время стирки.",
                pt: "Verifique o nível de lavagem.",
                nl: "Controleer het wasniveau.",
                fr: "Vérifier le niveau de lavage",
                it: "Controllare il livello di lavaggio",
                es: "Compruebe el nivel de lavado",
                pl: "Sprawdź poziom mycia",
                uk: "Перевірте рівень прання",
                "zh-cn": "检查洗涤液位",
            },
            checkDryLv: {
                en: "Check Dry Level",
                de: "Trockenheitsniveau prüfen",
                ru: "Проверьте уровень сухости",
                pt: "Verifique o nível de secura.",
                nl: "Controleer het droogniveau",
                fr: "Vérifier le niveau sec",
                it: "Verificare il livello di asciutto",
                es: "Comprobar el nivel de sequedad",
                pl: "Sprawdź poziom suchości",
                uk: "Перевірте рівень висихання",
                "zh-cn": "检查干液位",
            },
            checkNoiseLv: {
                en: "Check Noise Level",
                de: "Geräuschpegel prüfen",
                ru: "Проверьте уровень шума",
                pt: "Verifique o nível de ruído.",
                nl: "Controleer het geluidsniveau.",
                fr: "Vérifier le niveau sonore",
                it: "Verifica il livello di rumore",
                es: "Comprobar el nivel de ruido",
                pl: "Sprawdź poziom hałasu",
                uk: "Перевірте рівень шуму",
                "zh-cn": "检查噪音水平",
            },
            checkEnergy: {
                en: "Check energy",
                de: "Energie prüfen",
                ru: "Проверьте энергию",
                pt: "Verificar energia",
                nl: "Controleer de energie",
                fr: "Vérifier l'énergie",
                it: "Verifica l'energia",
                es: "Comprobar energía",
                pl: "Sprawdź energię",
                uk: "Перевірте енергію",
                "zh-cn": "检查能量",
            },
            checkTime: {
                en: "Check time",
                de: "Zeit prüfen",
                ru: "Проверьте время",
                pt: "Veja a hora",
                nl: "Controleer de tijd",
                fr: "Vérifiez l'heure",
                it: "Ora",
                es: "Ver hora",
                pl: "Sprawdź czas",
                uk: "Перевірити час",
                "zh-cn": "查看时间",
            },
            isReserveEndTime: {
                en: "Is Reserve End Time",
                de: "Ist Reserve Endzeit",
                ru: "Время окончания резерва",
                pt: "É o fim da reserva",
                nl: "Is de eindtijd van de reserve",
                fr: "Fin de la réserve",
                it: "È ora di fine riserva",
                es: "Reserve es hora de fin",
                pl: "Czy czas zakończenia rezerwy",
                uk: "Чи є час закінчення резерву",
                "zh-cn": "是预留结束时间吗",
            },
        };
    }
}

module.exports = Dishwasher;
